export type EdgeStatus = 'accepted' | 'excluded' | 'uncertain' | 'pending';
export interface CorpusLemma { lemma_id: string; language: string; word: string; normalized: string; search_form: string; frequency_score: number; category_breakdown: object; sources: object[]; corpus_quality: object; }
export interface ComponentCandidate { id: string; language: string; surface: string; associative_family_id: string | null; source_locator: object; evidence: object[]; }
export interface LexicalHead { id: string; language: string; normalized_head: string; identity_kind: 'lexical_head' | 'historically_reviewed_lexical_head' | 'legacy_exact_record'; sense: string; version: number; evidence: object[]; }
export interface AssociativeFamily { id: string; canonical: string; legacy_ids: string[]; canonical_decision: object; aliases: string[]; realizations: Record<string,string[]>; }
export type RealizationType = 'canonical_reflex' | 'lexical_branch_realization' | 'derivational_stem' | 'inflectional_form' | 'query_alias' | 'historical_evidence_form';
export interface NationalReflex { realization_type: RealizationType; head_scope: { language: string; normalized_head: string; sense: string; evidence: object[]; }[]; general_family_realization: boolean; establishes_membership: false; family_id: string; language: string; realization: string; morphology_boundary: string; supporting_heads: string[]; positive_controls: string[]; negative_controls: string[]; status: EdgeStatus; evidence: object[]; }
export interface EvidenceNode { legacy_id: string; etymon_keys: string[]; relation_evidence: object[]; source_locator: object; associative_family_id: null; }
export interface QueryAlias { query: string; original_query: string; query_key: string; source_evidence_key: string; language_scope: string | null; family_targets: string[]; family_routes: { family_id: string; language_scope: string | null; accepted_membership_count: number }[]; evidence_targets: string[]; evidence_routes: { id: string; kind: string; language_scope: string | null; source_alias_locator: { path: string; key: string; id: string }; establishes_membership: false }[]; establishes_membership: false; }
export interface HydratedCorpusRow extends CorpusLemma { accepted_memberships: { family_id: string; head_id: string; edge_version: number; source_proof: object[] }[]; }
export interface HeadFamilyEdge { head_id: string; family_id: string; status: EdgeStatus; scope: string; version: number; evidence: object[]; morphology_policy: string; lemma_ids: string[]; }
export interface LemmaHeadLink { link_role?: 'whole_lexeme' | 'inflection' | 'reviewed_lexical_base_component'; identity_fact_id?: string; whole_compound_identity_established?: false; component_segmentation?: object; identity_proof?: object[]; language: string; lemma_id: string; word: string; head_id: string; family_id: string; evidence: object[]; }
