import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {decideLexicalRow} from '../scripts/lib/associative-v6-senses-policy.mjs';
// Synthetic policy fixtures are separate from the real source rows below.
const fixture=()=>({membership_object:'lexical_row_or_component',formal_continuity:'accepted',component:'base',analyses:[{history:'shared',verdict:'accepted',evidence:['synthetic-proof'],proved_components:['base'],pos:'noun'},{history:'shared',verdict:'accepted',evidence:['synthetic-proof'],proved_components:['base'],pos:'verb'}]});
test('common base survives POS ambiguity without token or frequency claims',()=>{const r=decideLexicalRow(fixture());assert.equal(r.decision,'accepted');assert.equal(r.head_scope,'lexical_base_component');assert.equal(r.frequency_status,'aggregate_only_not_sense_frequency');assert.equal(r.token_senses_established,false);});
test('different lexical histories cannot be selected by dominant frequency',()=>{const x=fixture();x.analyses[1]={history:'unrelated',verdict:'excluded',evidence:['synthetic-proof'],frequency:0.0001};assert.equal(decideLexicalRow(x).decision,'deferred');x.analyses[1].verdict='accepted';assert.equal(decideLexicalRow(x).decision,'deferred');});
test('hypothetical name does not become observed pollution or a veto',()=>{const x=fixture();x.hypothetical_name=true;const r=decideLexicalRow(x);assert.equal(r.decision,'accepted');assert.equal(r.proper_name_observed,false);});
test('unproved morphology and missing lexical evidence remain blockers',()=>{const x=fixture();x.formal_continuity='withheld';assert.equal(decideLexicalRow(x).decision,'deferred');x.analyses[0].evidence=[];assert.throws(()=>decideLexicalRow(x));assert.throws(()=>decideLexicalRow({...fixture(),membership_object:'each_token'}));});
test('real 25-row adjudication preserves individual blockers and shared sistema base',()=>{const d=JSON.parse(fs.readFileSync('audit/associative-family-v6/prompt02-row-decisions-20261004.json'));assert.equal(d.rows.length,25);for(const r of d.rows)assert.equal(decideLexicalRow(r).decision,r.decision);assert.equal(d.rows.filter(r=>r.family_id==='family:anis'&&r.decision==='accepted').length,6);assert.deepEqual(d.rows.filter(r=>r.family_id==='family:turr'&&r.decision==='accepted').map(r=>r.language),[]);assert(d.rows.filter(r=>['tour','тура','tower','turm','turret'].includes(r.word)).every(r=>r.decision==='deferred'&&r.blocker));assert.equal(d.rows.find(r=>r.language==='it'&&r.family_id==='family:system').head_scope,'lexical_base_component');assert.equal(d.italian_anis_branch.branch_status,'accepted_dictionary_derivational_boundary_research_only');assert.equal(d.scope.blanket_pool_verdict,false);});
