import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {readPartitionDossier} from '../scripts/lib/associative-v6-contamination-io.mjs';
import {partitionReview,digest,FLAGS} from '../scripts/lib/associative-v6-contamination.mjs';
const row=(id='word',route='r',frame='synthetic',index=0)=>{const source_record={language:'xx',lemma_id:'synthetic:'+id,word:id,frequency_score:17,sources:[{ipm:2}],evidence:['synthetic-proof'],other_family_links:['sibling']},r={frame,route_id:route,language:'xx',lemma_id:source_record.lemma_id,word:id,locator:'synthetic#/'+route+'/'+index,source_sha256:'synthetic-source',source_record,source_record_sha256:digest(source_record)};r.incidence_id='incidence:'+digest([frame,route,r.language,r.lemma_id,r.locator,r.source_sha256]);return r;};
const branch=(id='branch',words=['word'],flags=[])=>({id,frame:'synthetic',head_scope:'national_only_research',review_state:'research',dictionary_supported_heads:['xx:word'],evidence_ids:['synthetic-dictionary'],evidence_gaps:['synthetic gap'],exact_records:words.map(word=>({frame:'synthetic',language:'xx',lemma_id:'synthetic:'+word,word})),flags,national_forms:[],formal_history:'synthetic finite history',canonical_approval:false,membership_authorized:false,family_id:null});
const run=(incidences,branches=[])=>partitionReview({incidences,branches,syntheticFixture:true});
test('synthetic: reused arrays conserve independent routes, measured payloads and sibling links',()=>{const rs=[row('word','r1'),row('word','r2')],before=structuredClone(rs),d=run(rs,[branch()]);assert.deepEqual(rs,before);assert.equal(d.metrics.unique_corpus_ids,1);assert.equal(d.metrics.incidences,2);assert.equal(d.metrics.flag_counts.alias_pool_reuse,1);assert.equal(d.metrics.flag_counts.duplicate_routing,1);assert.equal(d.incidences.length,2);assert(d.incidences.every(r=>r.source_record.other_family_links[0]==='sibling'));assert(d.records.every(r=>!r.accepted_membership_created&&!r.linguistic_exclusion_created));});
test('synthetic: homonymous canonical and multiple senses stay separate overlapping questions',()=>{const a=branch('valley'),b=branch('fort');a.candidate_canonical=b.candidate_canonical='vall';const d=run([row()],[a,b]);assert.equal(d.partitions.length,2);assert.deepEqual(d.records[0].branch_ids,['fort','valley']);assert.equal(d.metrics.overlapping_branch_questions,1);assert.equal(d.metrics.accepted_additions,0);});
test('synthetic: every unassigned occurrence has a separate unresolved route partition',()=>{const d=run([row('word','r1'),row('other','r1'),row('other','r2')],[branch()]);assert.equal(d.metrics.unassigned_questions,1);assert.equal(d.metrics.unresolved_partitions,2);assert.equal(new Set(d.partitions.flatMap(p=>p.incidence_ids)).size,3);});
for(const flag of FLAGS)test('synthetic: '+flag+' changes triage but creates no linguistic verdict',()=>{const d=run([row()],[branch('b',['word'],[flag])]);assert.equal(d.flags.find(f=>f.kind===flag).effect,'review_priority_and_state_only');assert.equal(d.records[0].review_state,'contamination_review_required');assert(d.records[0].review_priority>100);assert(!d.records[0].lexical_identity_proven&&!d.records[0].accepted_membership_created&&!d.records[0].linguistic_exclusion_created);});
test('synthetic: unknown or wrong-ID scopes, stale payload and repeated occurrence reject atomically',()=>{const r=row(),before=structuredClone(r);assert.throws(()=>run([r],[branch('b',['absent'])]),/Unknown/);const wrong=branch();wrong.exact_records[0].word='wrong';assert.throws(()=>run([r],[wrong]),/wrong-ID/);assert.throws(()=>run([r,r]),/Duplicate/);assert.throws(()=>run([{...r,source_record_sha256:'stale'}]),/Stale/);assert.deepEqual(r,before);});
test('synthetic: authority leaks, unknown flags and undocumented dictionary heads reject',()=>{for(const edit of [b=>b.membership_authorized=true,b=>b.canonical_approval=true,b=>b.family_id='family:x',b=>b.flags=['unknown'],b=>b.evidence_ids=[],b=>b.national_forms=[{general_realization_authorized:true}]]){const b=branch();edit(b);assert.throws(()=>run([row()],[b]));}assert.throws(()=>partitionReview({incidences:[row()],branches:[]}),/Synthetic real/);});
test('synthetic: deterministic replay and input permutation conserve exact evidence',()=>{const rs=[row('word','r2'),row('other','r1')],bs=[branch()];assert.deepEqual(run(rs,bs),run([...rs].reverse(),bs));assert.deepEqual(run(rs,bs),run(rs,bs));});
test('real: val Russian and independent tower conservation; permanent negatives remain separate',()=>{const p='audit/associative-family-v6/prompt07-contamination-20261005/generated/',d=readPartitionDossier(p),replay=partitionReview({incidences:d.incidences,branches:d.partitions.filter(b=>b.kind!=='unresolved_partition').map(({corpus_ids,incidence_ids,source_payload_hashes,linguistic_adjudication_created,accepted_membership_created,...b})=>b)});assert.deepEqual(replay,d,'Exact real deterministic reconstruction');assert.equal(d.metrics.frames.russian.unique_ids,2633);assert.equal(d.metrics.frames.val.unique_ids,5516);assert.equal(d.metrics.frames.tower.unique_ids,1083);assert(d.partitions.some(p=>p.id==='ru.um.mental'&&p.head_scope==='national_only_research'));assert(d.flags.some(f=>f.kind==='semantic_translation_gloss'&&f.corpus_ids.some(id=>id.startsWith('ru\0'))));assert.equal(d.metrics.accepted_additions,0);assert.equal(d.metrics.accepted_removals,0);});

test('real: system→состав and botanical anis→scientific aniso never enter current accepted search',()=>{const memberships=JSON.parse(gunzipSync(fs.readFileSync('associativvordes/family-index-v6/generated/memberships.json.gz')));assert(!memberships.some(r=>r.family_id==='family:system'&&r.word==='состав'));assert(!memberships.some(r=>r.family_id==='family:anis'&&r.word==='anisotropy'));assert(memberships.some(r=>r.family_id==='family:system'&&r.word==='система'));assert(memberships.some(r=>r.family_id==='family:anis'&&r.word==='anise'));});
