import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {FamilyIndexLoader,familyBucket} from '../associativvordes/js/family-index-loader.js';
const root='associativvordes/family-index-v5';
const read=async p=>JSON.parse((p.endsWith('.gz')?gunzipSync(await readFile(p)):await readFile(p)).toString());
test('materialization removes only eleven reviewed inter links and preserves positive component records',async()=>{
 const ledger=await read('audit/associative-family-v5/component-review-20261001.json');
 const id='family:inter',members=(await read(`${root}/members/en/${familyBucket(id)}.json.gz`))[id];
 const rejected=new Set(ledger.decisions.filter(d=>d.verdict==='remove_membership').map(d=>d.word));
 const inspected=ledger.inspected_arrays.find(a=>a.family_id===id);
 assert.equal(members.length,inspected.count-11);
 const reconstructed=new Map(members.map(m=>[m.word,m]));
 for(const d of ledger.decisions.filter(d=>d.verdict==='remove_membership'))reconstructed.set(d.word,d.original_member);
 assert.equal(createHash('sha256').update(JSON.stringify(inspected.words.map(w=>reconstructed.get(w)))).digest('hex'),inspected.ordered_member_sha256);
 assert.deepEqual(members.map(m=>m.word),inspected.words.filter(w=>!rejected.has(w)));
 for(const d of ledger.decisions.filter(d=>d.verdict==='retain'))assert.deepEqual(members.find(m=>m.lemma_id===d.lemma_id),d.original_member);
 const loader=new FamilyIndexLoader({baseUrl:root,fetchJson:async p=>read(p)});
 const result=await loader.candidateEntries('inter','en');
 assert.deepEqual(result.map(m=>m.word).sort(),['interdisciplinary','international','internet','interval']);
 const nato='ety:496b7cec5a43',family=(await read(`${root}/families/${familyBucket(nato)}.json.gz`))[nato];
 assert.deepEqual(family,{...ledger.family_metadata[nato],aliases:ledger.family_metadata[nato].aliases.filter(a=>a!=='nat')});
 const nat=(await read(`${root}/aliases/${familyBucket('nat')}.json.gz`)).nat;
 assert(!nat.includes(nato));
 const acronymRoute=(await read(`${root}/aliases/${familyBucket('nato')}.json.gz`)).nato;
 assert(acronymRoute.includes(nato));
});
