import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { LANGUAGE_SOURCES } from '../associativvordes/js/config-frequency-sources.js';
import { globalConfigHash, languageConfigHash } from '../scripts/build-associative-candidate-index.mjs';

const node = process.execPath;
const script = 'scripts/build-associative-candidate-index.mjs';
const fixtureRoot = 'tests/fixtures/associative-frequency';
const outputRoot = '.tmp/associative-index-test';

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'));
}

function run(args, options = {}) {
  return spawnSync(node, [script, ...args], { encoding: 'utf8', ...options });
}

function assertCanonicalShardOrder(entries, message) {
  const keys = entries.map(entry => `${entry.search_form}\0${entry.normalized}\0${entry.word}`);
  assert.deepEqual(keys, [...keys].sort((a, b) => a.localeCompare(b)), message);
}

async function build(extra = [], out = outputRoot) {
  await rm(out, { recursive: true, force: true });
  const result = run(['--languages=en', `--input-root=${fixtureRoot}`, `--output-root=${out}`, '--max-records=5000', ...extra]);
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return { manifest: await readJson(join(out, 'manifest.json')), entries: await readJson(join(out, 'en', 'a.json')) };
}

const first = await build();
assert.ok(existsSync(join(outputRoot, 'manifest.json')), 'creates manifest');
assert.ok(first.manifest.languages.en.shards.length > 0, 'creates shards');
assert.ok(existsSync(join(outputRoot, 'en', 'a.json')), 'creates letter shard');
assert.ok(existsSync(join(outputRoot, 'en', '_other.json')), 'creates _other shard');

const alternative = first.entries.find(entry => entry.normalized === 'alternative');
assert.ok(alternative, 'keeps alternative');
assert.equal(first.entries.filter(entry => entry.normalized === 'alternative').length, 1, 'merges duplicates');
const hermitSource = alternative.sources.find(source => source.id.includes('hermit_2016'));
const bncSource = alternative.sources.find(source => source.id.includes('bnc-clean2'));
assert.ok(hermitSource, 'preserves sources');
assert.ok(bncSource, 'preserves multiple sources');
assert.deepEqual(Object.keys(hermitSource), ['id', 'file', 'category', 'ipm'], 'builder creates canonical source shape');
assert.equal(hermitSource.id, `${hermitSource.category}/${hermitSource.file}`, 'source id is category/file');
assert.equal(hermitSource.category, 'subtitles', 'source category comes from LANGUAGE_SOURCES category');
assert.ok(LANGUAGE_SOURCES.en[hermitSource.category].includes(hermitSource.file), 'source category matches LANGUAGE_SOURCES');
assert.equal(hermitSource.file.includes('/'), false, 'source file is a bare file name');
assert.equal(hermitSource.file.includes('\\'), false, 'source file does not contain a Windows path separator');
assert.equal(bncSource.category, 'normative', 'normative source category comes from LANGUAGE_SOURCES');
assert.equal(alternative.rank, null, 'does not treat rank as output IPM');
assert.ok(Number.isFinite(alternative.frequency_score), 'frequency_score finite');
assert.ok(alternative.frequency_score >= 0 && alternative.frequency_score <= 100, 'frequency_score range');
assert.equal(first.manifest.global_config_hash.length, 64, 'global_config_hash present');
assert.equal(first.manifest.languages.en.language_config_hash.length, 64, 'language_config_hash present');
assertCanonicalShardOrder(first.entries, 'builder writes a shard in canonical search_form/normalized/word order');


const reportOut = '.tmp/associative-index-test-report';
await rm(reportOut, { recursive: true, force: true });
const reportRun = run(['--languages=en', `--input-root=${fixtureRoot}`, `--output-root=${reportOut}`, '--max-records=5000', `--report=${reportOut}/build-report.json`]);
assert.equal(reportRun.status, 0, reportRun.stderr || reportRun.stdout);
const report = await readJson(join(reportOut, 'build-report.json'));
assert.equal(report.language, 'en', 'report stores language');
assert.equal(report.entries, first.manifest.languages.en.entries, 'report stores entry count');
assert.ok(report.duplicates_merged > 0, 'report stores merged duplicates');
assert.equal(report.invalid_records, 0, 'report stores invalid record count');
assert.deepEqual(report.source_files, first.manifest.languages.en.source_files, 'report stores real source files');
assert.deepEqual(report.shards, first.manifest.languages.en.shards, 'report stores shard summary');
assert.ok(report.total_bytes > 0, 'report stores generated byte count');
assert.deepEqual(Object.keys(report.root_samples), ['alter', 'regul', 'ocul', 'inter'], 'report stores expected root samples');
assert.ok(report.root_samples.alter.length <= 20, 'report limits alter samples');
assert.ok(report.root_samples.alter.map(word => word.toLowerCase()).includes('alternative'), 'report root samples come from built entries');

const second = await build([], '.tmp/associative-index-test-2');
assert.equal(first.manifest.global_config_hash, second.manifest.global_config_hash, 'global_config_hash deterministic');
const firstManifestNoDate = { ...first.manifest, generated_at: 'ignored-a' };
const secondManifestNoDate = { ...second.manifest, generated_at: 'ignored-b' };
assert.equal(firstManifestNoDate.global_config_hash, secondManifestNoDate.global_config_hash, 'generated_at does not affect global_config_hash');
assert.deepEqual(first.entries, second.entries, 'repeat build gives same entries');

const limited = await build(['--max-records=1'], '.tmp/associative-index-test-limited');
assert.equal(limited.manifest.languages.en.entries, 1, '--max-records limits processing');

await rm('.tmp/associative-index-no-write', { recursive: true, force: true });
const noWrite = run(['--languages=en', `--input-root=${fixtureRoot}`, '--output-root=.tmp/associative-index-no-write', '--max-records=5000', '--no-write']);
assert.equal(noWrite.status, 0, noWrite.stderr || noWrite.stdout);
assert.equal(existsSync('.tmp/associative-index-no-write'), false, '--no-write does not create files');

const dryRun = run(['--languages=en', `--input-root=${fixtureRoot}`, '--output-root=.tmp/associative-index-dry-run', '--max-records=2', '--dry-run', '--no-write']);
assert.equal(dryRun.status, 0, dryRun.stderr || dryRun.stdout);
const dryRunStats = JSON.parse(dryRun.stdout);
assert.deepEqual(Object.keys(dryRunStats), ['language', 'source_file', 'records_read', 'valid_lemmas', 'invalid_records', 'duplicate_lemmas', 'lemmas_with_search_form', 'lemmas_without_search_form', 'min_ipm', 'max_ipm', 'min_frequency_score', 'max_frequency_score', 'root_samples'], 'dry-run prints compact diagnostics only');
assert.equal(dryRunStats.language, 'en');
assert.equal(dryRunStats.records_read, 2);
assert.equal(dryRunStats.valid_lemmas, 2);
assert.equal(dryRunStats.lemmas_with_search_form, 2);
assert.equal(dryRunStats.lemmas_without_search_form, 0);
assert.ok(dryRunStats.max_ipm >= dryRunStats.min_ipm);
assert.deepEqual(Object.keys(dryRunStats.root_samples), ['alter', 'regul', 'ocul', 'inter']);
assert.equal(JSON.stringify(dryRunStats).includes('category_breakdown'), false, 'diagnostics do not print full dictionary entries');
assert.equal(existsSync('.tmp/associative-index-dry-run'), false, '--dry-run --no-write does not create files');

const invalid = run(['--languages=en', '--input-root=tests/fixtures/associative-frequency-invalid', '--output-root=.tmp/associative-index-invalid', '--max-records=5000']);
assert.notEqual(invalid.status, 0, 'data errors exit non-zero');

await rm('.tmp/associative-frequency-canonical', { recursive: true, force: true });
await cp(fixtureRoot, '.tmp/associative-frequency-canonical', { recursive: true });
const canonicalWebFile = join('.tmp/associative-frequency-canonical', 'en', 'sorted.uk.lemma.unigrams.cleaned_recommended_min100_ipm6.json');
const canonicalWeb = await readJson(canonicalWebFile);
canonicalWeb.zzzfirst = 100;
canonicalWeb.aaalast = 1;
await writeFile(canonicalWebFile, `${JSON.stringify(canonicalWeb, null, 2)}\n`);
await rm('.tmp/associative-index-canonical', { recursive: true, force: true });
const canonicalRun = run(['--languages=en', '--input-root=.tmp/associative-frequency-canonical', '--output-root=.tmp/associative-index-canonical', '--max-records=5000']);
assert.equal(canonicalRun.status, 0, canonicalRun.stderr || canonicalRun.stdout);
const canonicalA = await readJson('.tmp/associative-index-canonical/en/a.json');
assertCanonicalShardOrder(canonicalA, 'builder creates shard in canonical order');
assert.ok(canonicalA.findIndex(entry => entry.normalized === 'aaalast') < canonicalA.findIndex(entry => entry.normalized === 'alternative'), 'frequency does not define physical shard order');

await rm('.tmp/associative-frequency-reordered', { recursive: true, force: true });
await mkdir('.tmp/associative-frequency-reordered/en', { recursive: true });
const files = [
  'hermit_2016_en_full_lemmatized_ipm6_spacy_lookup_cleaned_v8.json',
  'hermit_2018_en_full_lemmatized_ipm6_spacy_lookup_cleaned_v8.json',
  'bnc-clean2.lemmatized_spacy_ipm6.json',
  'sorted.uk.lemma.unigrams.cleaned_recommended_min100_ipm6.json'
];
for (const file of files) {
  const data = await readJson(join(fixtureRoot, 'en', file));
  if (Array.isArray(data)) data.reverse();
  else {
    const reversed = Object.fromEntries(Object.entries(data).reverse());
    await writeFile(join('.tmp/associative-frequency-reordered/en', file), `${JSON.stringify(reversed, null, 2)}\n`);
    continue;
  }
  await writeFile(join('.tmp/associative-frequency-reordered/en', file), `${JSON.stringify(data, null, 2)}\n`);
}
await rm('.tmp/associative-index-reordered', { recursive: true, force: true });
const reorderedRun = run(['--languages=en', '--input-root=.tmp/associative-frequency-reordered', '--output-root=.tmp/associative-index-reordered', '--max-records=5000']);
assert.equal(reorderedRun.status, 0, reorderedRun.stderr || reorderedRun.stdout);
assert.deepEqual(await readJson('.tmp/associative-index-reordered/en/a.json'), first.entries, 'input order does not affect output');

assert.equal(existsSync('associativvordes/candidate-index'), false, '.tmp does not write production candidate-index');
assert.match(await readFile('.gitignore', 'utf8'), /^\.tmp\/$/m, '.tmp ignored');

async function buildLanguageFixture(language, out) {
  await rm(out, { recursive: true, force: true });
  const result = run([`--languages=${language}`, `--input-root=${fixtureRoot}`, `--output-root=${out}`, '--max-records=5000']);
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return { manifest: await readJson(join(out, 'manifest.json')) };
}

async function readAllLanguageEntries(out, language) {
  const manifest = await readJson(join(out, 'manifest.json'));
  const entries = [];
  for (const shard of manifest.languages[language].shards) entries.push(...await readJson(join(out, shard.file)));
  return entries;
}


const enOnly = first;
const ruOnly = await buildLanguageFixture('ru', '.tmp/associative-index-ru');
assert.equal(enOnly.manifest.global_config_hash, ruOnly.manifest.global_config_hash, 'separate en and ru builds share global_config_hash');
assert.notEqual(enOnly.manifest.languages.en.language_config_hash, ruOnly.manifest.languages.ru.language_config_hash, 'en and ru language_config_hash values differ');
assert.notEqual(globalConfigHash({ baseCategoryWeights: { subtitles: 0.31, normative: 0.29, web: 0.30, mixed: 0.10 } }), enOnly.manifest.global_config_hash, 'changing global weights changes global_config_hash');
assert.notEqual(languageConfigHash('ru', { languageSources: { ru: { subtitles: ['hermit_2018_ru_full_lemmatized_pymorphy3_ipm6.json'], normative: ['changed-source.json'], web: ['ruwac.out.gz.lpos-clean2-biwt.cleaned_recommended_min100_ipm6.json'], mixed: [] } } }), ruOnly.manifest.languages.ru.language_config_hash, 'changing only ru sources changes ru language_config_hash');

for (const language of ['de', 'fr', 'es', 'it']) {
  await buildLanguageFixture(language, `.tmp/associative-index-${language}`);
}

const deEntries = await readAllLanguageEntries('.tmp/associative-index-de', 'de');
const deAenderung = deEntries.find(entry => entry.normalized === 'änderung');
assert.equal(deAenderung.word, 'Änderung', 'German original form is preserved');
assert.equal(deAenderung.search_form, 'anderung', 'German umlaut is stripped only in search_form');
assert.equal(deEntries.find(entry => entry.normalized === 'größe').search_form, 'grosse', 'ß becomes ss in search_form');
assert.equal(deEntries.find(entry => entry.normalized === 'küche').search_form, 'kuche', 'ü is stripped in search_form');
const deDoppel = deEntries.find(entry => entry.normalized === 'doppel');
assert.equal(deDoppel.sources.length, 3, 'German duplicate sources are merged without loss');
assert.equal(deEntries.find(entry => entry.normalized === 'nullwert').category_breakdown.normative.category_ipm, 0, 'zero IPM is not a positive observation');
assert.equal(deEntries.some(entry => entry.normalized === 'rangnur'), false, 'rank-only German record is rejected');

const frEntries = await readAllLanguageEntries('.tmp/associative-index-fr', 'fr');
const regulation = frEntries.find(entry => entry.normalized === 'régulation');
assert.equal(regulation.word, 'régulation', 'French diacritic is preserved in word');
assert.equal(regulation.search_form, 'regulation', 'French diacritic is stripped in search_form');
assert.equal(frEntries.find(entry => entry.normalized === 'mère').search_form, 'mere');
assert.equal(frEntries.find(entry => entry.normalized === 'forêt').search_form, 'foret');
assert.equal(frEntries.find(entry => entry.normalized === 'façade').search_form, 'facade');
assert.equal(frEntries.find(entry => entry.normalized === "l’amour").search_form, "l'amour", 'Unicode apostrophe normalizes consistently');
assert.equal(frEntries.find(entry => entry.normalized === 'avant-garde').search_form, 'avant-garde', 'hyphen preserves word boundary');
assert.equal(frEntries.find(entry => entry.normalized === 'doublon').sources.length, 2, 'French duplicate sources are merged');

const esEntries = await readAllLanguageEntries('.tmp/associative-index-es', 'es');
assert.equal(esEntries.find(entry => entry.normalized === 'regulación').search_form, 'regulacion', 'Spanish accent is stripped in search_form');
assert.equal(esEntries.find(entry => entry.normalized === 'niño').search_form, 'nino', 'Spanish ñ is normalized deterministically');
assert.equal(esEntries.find(entry => entry.normalized === 'casa').search_form, 'casa', 'Spanish ASCII form is preserved in search_form');
assert.equal(esEntries.find(entry => entry.normalized === 'duplicado').sources.length, 3, 'Spanish duplicate sources are merged');
assert.equal(esEntries.some(entry => entry.normalized === 'rango'), false, 'rank-only Spanish record is rejected');

const itEntries = await readAllLanguageEntries('.tmp/associative-index-it', 'it');
assert.equal(itEntries.find(entry => entry.normalized === 'città').word, 'città', 'Italian diacritic is preserved');
assert.equal(itEntries.find(entry => entry.normalized === 'città').search_form, 'citta', 'Italian diacritic is stripped in search_form');
assert.equal(itEntries.find(entry => entry.normalized === "l’amico").search_form, "l'amico", 'Italian apostrophe normalizes consistently');
assert.equal(itEntries.find(entry => entry.normalized === 'regolazione').search_form, 'regolazione', 'Italian ASCII search_form remains unchanged');
assert.equal(itEntries.find(entry => entry.normalized === 'duplicato').sources.length, 3, 'Italian duplicate sources are merged');

await rm('.tmp/associative-index-ru-dry-run', { recursive: true, force: true });
const ruDryRun = run(['--languages=ru', `--input-root=${fixtureRoot}`, '--output-root=.tmp/associative-index-ru-dry-run', '--source-file=rnc-orig.out.lpos-clean2-biwt.cleaned_ipm6.json', '--max-records=3', '--dry-run', '--no-write']);
assert.equal(ruDryRun.status, 0, ruDryRun.stderr || ruDryRun.stdout);
const ruDryRunStats = JSON.parse(ruDryRun.stdout);
assert.equal(ruDryRunStats.language, 'ru', 'Russian dry-run reports language');
assert.equal(ruDryRunStats.source_file, 'normative/rnc-orig.out.lpos-clean2-biwt.cleaned_ipm6.json', 'Russian dry-run preserves source file');
assert.equal(ruDryRunStats.records_read, 3, 'Russian dry-run respects --max-records');
assert.equal(ruDryRunStats.valid_lemmas, 3, 'Russian dry-run extracts valid lemmas');
assert.equal(ruDryRunStats.lemmas_with_search_form, 3, 'Russian dry-run creates search_form');
assert.equal(ruDryRunStats.lemmas_without_search_form, 0, 'Russian dry-run has no missing search_form');
assert.equal(ruDryRunStats.min_ipm, 2.8, 'Russian dry-run extracts IPM, not rank');
assert.equal(ruDryRunStats.max_ipm, 4.2, 'Russian dry-run reports max IPM from source values');
assert.ok(ruDryRunStats.min_frequency_score >= 0, 'Russian frequency_score is non-negative');
assert.equal(existsSync('.tmp/associative-index-ru-dry-run'), false, 'Russian dry-run no-write does not create files');
assert.equal(JSON.stringify(ruDryRunStats).includes('category_breakdown'), false, 'Russian diagnostics do not print full dictionary entries');
