"""Explicit partial loc reflex adjudication; does not mutate runtime or relabel the backlog."""
import gzip,json,hashlib
from pathlib import Path
base=Path('audit/associative-family-v5')
source=base/'component-checkpoint-20261001/candidate-records.json.gz'
candidates=json.load(gzip.open(source,'rt'))['loc']
ru_heads='''билокационный билокация биолокационный биолокация геолокационный геолокация георадиолокатор гидролокатор гидролокация делокализация дислокация звуколокация локализатор локализационный локализация локализировать локализованный локализовать локализоваться локалка локаль локально локальность локальный локатив локатор локаторный локаторщик локационный локация локомобиль локомотив локомотивный локомотор локомоторный локомоция локус нелокальность нелокальный передислокация противорадиолокационный радиолокатор радиолокационный радиолокация релокационный релокация транслокационный транслокация узколокализовать шпионолокатор электролокация эхолокатор эхолокационный эхолокация'''.split()
de_stems=['lokal','lokom','lokati','lokus','lokativ']
de_excluded={'flokati':'Greek flokati rug name, not the Latin place root.','kilokalorie':'kilo + Kalorie: lokal crosses the morpheme boundary.','kilokalorien':'kilo + Kalorien: lokal crosses the morpheme boundary.','holokalyptischer':'holo + kalyptisch: overlap crosses the morpheme boundary.','molokomilch':'Named product/foreign moloko element; no place-root compound.'}
de_uncertain=set('aiesec-lokalkomitees gastanzlokalen gea-lokaltermine glokal glokales glokalisierung lokalfernsehstars lokali lokaliban lokalis lokaliseren lokalisier lokalisierungs lokaljournalis-tinnen lokatisiert lokomaika lokomotiv lokomotivbetriebs lokomotivedampf lokomotivpersonals mountain-lokomotiven polokus stiplokal striplokalwirft südkurier-lokalredaktion sz-lokalausgabe us-lokalmatadorin'.split())
ru_excluded={'англокатолик':'англо + католик: локат crosses a compound boundary.','бета-блокаторы':'бета + блокатор derives from block, not locus.','бетаблокатор':'бета + блокатор derives from block, not locus.','блокатор':'block derivative, not the place root.','блокус':'Named game/token, no established place-root derivative.','велокомпьютер':'вело + компьютер: локом crosses a compound boundary.','волокать':'Native волок- drag stem, unrelated to locus.','волоком':'Native волок- drag stem, unrelated to locus.','килокалория':'кило + калория: локал crosses a compound boundary.','креслокаталка':'кресло + каталка: локат crosses a compound boundary.','малокалиберный':'мало + калиберный: локал crosses a compound boundary.','малокалорийный':'мало + калорийный: локал crosses a compound boundary.','малокомпетентный':'мало + компетентный: локом crosses a compound boundary.','малокомплектный':'мало + комплектный: локом crosses a compound boundary.','нейроблокатор':'нейро + блокатор: block branch, not locus.','околокомпьютерный':'около + компьютерный: локом crosses a compound boundary.','поволокать':'Native волок- drag stem, unrelated to locus.','холиноблокатор':'холино + блокатор: block branch, not locus.','шерлоком':'Inflected proper name Шерлок, not a place-root derivative.'}
de_more=set("""abschlepplok dampflok dampflokbestand dampflokeldorados dampflokfahrten dampflokführer dampflokgeräusche dampflokpfeife dampfloks dampflokzuschlag diesel-industrieloks diesel-lok diesellok dieselloks e-lok elektrolok ersatz-loks hauptlok lok lok-fahrer lokadresse lokator lokatoren lokbaureihen lokbesatzung lokbespannte lokführer lokführer-gewerkschaft lokführer-streik lokführergewerkschaft lokführerin lokführern lokführers lokführerstreik lokhälfte lokpfeife lokpfeifen lokrahmen lokrangierführer loks lokschuppen lokschuppenfront loksound lokvorräte lokzug museumslok nohab-loks original-zahnrad-dampfloks ringlokschuppen sbb-lok sbb-lokführer spielzeuglok streckendiesellok tenderlok todeslok translokator translokatorsteuerung unglückslok vorspannlok wendeloks zuglok zweizylinderloks""".split())
de_boundary=['cello','violoncello','solo','holo','phallo','staph','stapyl','silo','kloka','klokas','kloki','klokopf','klokrie','hallok','würfelokta','weitwinkelokul','talokrural']
ru_boundary=['блок','волок','белок','молок','яблок','локот','локт','колокол','стафил','стаффил','страфил','стеклок','металлок','теплок','малок','светлок','смуглок','злок','велок','силокс','флок','холок','голок','фаллок','кило','креслок']
result=[]
for lang,records in candidates.items():
 if lang not in ['de','ru']:continue
 for m in records:
  w=m['word'].lower()
  selected=('lok' in w) if lang=='de' else ('лок' in w)
  if not selected:continue
  status='uncertain';reason='Needs lexical/corpus-context confirmation; withheld from membership.'
  negatives=de_excluded if lang=='de' else ru_excluded
  if w in negatives:status='excluded';reason=negatives[w]
  elif lang=='ru' and w in ru_heads:status='accepted';reason='Explicitly reviewed lexical derivative or transparent compound of place/placement/motion loc~лок; full international element retained.'
  elif lang=='de' and w in de_more:
   status='accepted';reason='Explicitly reviewed locomotive/locator head or transparent compound. Lok preserves the German root form as the dictionary-attested shortening of Lokomotive; no arbitrary name token is admitted.'
  elif lang=='de' and any(stem in w for stem in de_stems) and w not in de_uncertain:
   stem=next(s for s in de_stems if s in w);status='accepted';reason=f'Explicitly reviewed German lexical head, inflection or productive compound around {stem}; place/placement/motion element loc~lok is intact.'
  if status=='uncertain' and ((lang=='de' and any(w.startswith(stem) for stem in de_boundary)) or (lang=='ru' and any(stem in w for stem in ru_boundary))):
   status='excluded';reason='Token belongs to an identifiable independent native/borrowed stem or compound boundary collision, not the Latin place/placement/motion element: '+w
  result.append({'language':lang,'lemma_id':m['lemma_id'],'word':m['word'],'status':status,'reason':reason})
counts={lang:{s:sum(r['language']==lang and r['status']==s for r in result) for s in ['accepted','excluded','uncertain']} for lang in ['de','ru']}
artifact={'source_run_id':35647932153,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'root':'loc','proposed_surface_forms':{'de':['loc','lok'],'ru':['лок']},'scope':'Review of every loc~lok/лок spelling candidate in the immutable loc checkpoint from immutable complete source checkpoint. Other candidates retain prior unresolved state. This ledger is not yet materialized.','decisions':result,'counts':counts,'sources':[{'url':'https://www.duden.de/rechtschreibung/lokal','supports':'localis/locus origin and place meaning'},{'url':'https://www.duden.de/rechtschreibung/Lokation','supports':'locatio/locare/locus origin'},{'url':'https://www.duden.de/rechtschreibung/Lokomotive','supports':'locomotive motion branch'},{'url':'https://www.duden.de/rechtschreibung/Lokomotion','supports':'locus plus motio'},{'url':'https://gramota.ru/poisk?mode=slovari&query=локатор','supports':'locare placement origin'},{'url':'https://gramota.ru/poisk?mode=all&query=локальный','supports':'localis origin'},{'url':'https://gramota.ru/poisk?mode=slovari&query=локатив','supports':'casus locativus'}],'limitations':['Head etymologies support transparent productive analyses; not every compound has an independent dictionary entry.','Named/fused/unclear tokens are withheld.','Abbreviated Lok compounds and other reflex candidates outside the explicit selected stems still require review.','No runtime acceptance before immutable-source, independent-component and route-preservation preflight.']}
(base/'loc-reflex-decisions-20261001.json').write_text(json.dumps(artifact,ensure_ascii=False,indent=2)+'\n');print(json.dumps(counts))
