import json,gzip,pathlib,hashlib
root=pathlib.Path('associativvordes/family-index-v5');proofs={}
def read(p):
 b=p.read_bytes();proofs[str(p)]=hashlib.sha256(b).hexdigest();return json.loads(gzip.decompress(b) if str(p).endswith('.gz') else b)
def bucket(id):
 h=0x811c9dc5
 for c in id:h=((h^ord(c))*0x01000193)&0xffffffff
 return format(h%256,'02x')
ids=['ety:e5b5bac756da','ety:82f27619decc','ety:d23b06bd3000','ety:fe15b78c8368'];metadata=[]
for id in ids:
 p=root/'families'/(bucket(id)+'.json.gz');f=read(p)[id];metadata.append({'legacy_id':id,'source':str(p),'etymon_keys':f.get('etymon_keys',[]),'aliases':f['aliases'],'source_declared_terms':sorted(set(e['sourceLang']+':'+e['term'] for e in f.get('relation_evidence',[]) if e.get('sourceLang') and e.get('term')))})
source_id=ids[0];heads=[]
plan=[('en','system','system','https://www.merriam-webster.com/dictionary/system'),('de','system','system','https://www.duden.de/rechtschreibung/System'),('fr','système','système','https://www.dictionnaire-academie.fr/article/A9S3967'),('es','sistema','sistema','https://dle.rae.es/sistema'),('it','sistema','sistema','https://www.treccani.it/vocabolario/sistema/'),('ru','система','система','https://gramota.ru/poisk?mode=slovari&query=%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0%D1%85')]
for lang,word,head,dictionary in plan:
 id='surface:ru:sistem' if lang=='ru' else source_id;p=root/'members'/lang/(bucket(id)+'.json.gz');rs=read(p)[id];matches=[r for r in rs if r['word']==word];assert len(matches)==1;r=matches[0]
 heads.append({'language':lang,'normalized_head':head,'sense':'structured_assembly_or_scheme','identity_fact_status':'independently_supported_lexical_row','finite_source_record':r,'source':str(p),'source_container_id':id,'dictionary_source':dictionary,'membership_status':'pending_new_family_promotion','identity_binding_authorized':False})
p=root/'members/ru'/(bucket(source_id)+'.json.gz');ru=read(p)[source_id];assert len(ru)==24;counter=[r for r in ru if r['word']=='состав'];assert len(counter)==1
clusterPath=pathlib.Path('audit/associative-family-v6/candidate-root-clusters-20261003/clusters.json.gz');clusters=read(clusterPath);packets=[c['candidate_cluster_id'] for c in clusters if any(id in c['evidence_cluster_ids'] for id in ids)];assert len(packets)==2
out={'preparation_script':'scripts/prepare-associative-v6-system-promotion-research.py','script_sha256':hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),'schema_version':6,'stage':'system-international-promotion-research-20261003','source_head':'7a40c30e9d95f8c64d9e0cd40d2d560bbc6808e0','production_enabled':False,'binding_authorized':False,'accepted_membership_authorized':False,'status':'promotion_research_requires_catalog_and_finite_corpus_frame','candidate_packets':packets,'source_evidence_clusters':metadata,'independent_head_facts':heads,'canonical_boundary_review':{'proposed_base':'system','canonical_decision':None,'status':'explicit_linguistic_recommendation_not_catalog_approval','rationale':'The whole modern English/German lexical base system recurs in independently attested French, Spanish, Italian and Russian loans from Greek systēma through Latin or French mediation. This is a recommendation based on the whole international lexical row, not shortest substring selection. systema keeps the longer full source noun form rather than the compact modern international head; this recommendation is not a general Greek/Latin ending-removal rule. syst and sys cut recognizability. Greek/Latin systemat- in derivations must be modeled as a branch stem, not a reason to invent substring membership. Preserve both ped under-stripping and creat over-stripping controls.','under_stripping_candidate':'systema','over_stripping_candidates':['syst','sys'],'derivational_stem_requires_separate_review':'systemat'},'national_form_review':[{'language':l,'lexical_form':w,'status':'proved_noun_head_form_not_general_reflex'} for l,w,h,s in plan],'negative_alias_control':{'alias':'sostav','word':'состав','source_record':counter[0],'source':str(p),'finding':'The Russian lexical translation состав is not the borrowed system element. The entire 24-record Russian pool in the Greek container must not be promoted on semantic similarity. The actual система record is independently frozen from surface:ru:sistem.','source_pool_records':24,'automatic_membership_removal':False},'new_catalog_promotions':0,'new_memberships':0,'current_queue_records_resolved':0,'input_sha256':proofs,'limitations':['Independent dictionaries establish the international lexical row, not every compound or all legacy member arrays.','No source etymological or surface container is imported wholesale.','Corpus part-of-speech and sense ambiguity, including sistema verb forms, must be scoped before noun identity binding.','General national reflexes and additional morphology require separate evidence.','Promotion must extend the existing catalog and exact finite frame; the six current seed queues cannot stand in for that frame.','This explicitly unauthorized research recipe cannot be passed into the existing stage integrator.']}
pathlib.Path('audit/associative-family-v6/system-promotion-research-20261003.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print('Six independently supported head rows, six real corpus IDs, two candidate packets, zero promotions; translation contamination preserved as a counterexample.')
