"""Mutation/change/exchange review with explicit separation of homonyms."""
import json,gzip,hashlib,unicodedata,re
from pathlib import Path
base=Path('audit/associative-family-v5');out=base/'mutation-checkpoint-20261001';out.mkdir(exist_ok=True)
fold=lambda w: ''.join(c for c in unicodedata.normalize('NFKD',w.lower()) if not unicodedata.combining(c))
selected={
'en':'''antimutagen antimutant commutable commutate commutating commutation commutational commutative commutator commutatorless commute commuter commuters commuting demutate demutated demutation demutualisation dismutase hypermutation immutability immutable immutably megamutant mutability mutable mutagen mutagenesis mutagenic mutagenicity mutagenized mutancy mutandis mutant mutantkind mutantous mutants mutate mutation mutational mutations mutatis mutative mutator mutators mutual mutualism mutualist mutualistic mutuality mutually mutuals non-commutative noncommutative parimutuel permutate permutation permute retromutagen supermutants telecommute telecommuted telecommuter telecommutes telecommuting transmutate transmutated transmutation transmutational transmutationist transmutative transmutator transmute transmuter unmutated unmutual unmutualism unmutuals''',
'fr':'''autocommutateur commutable commutateur commutatif commutatifs commutation commutations commutative commutativité commuter dismutase immutabilité immutable mutabilité mutable mutagene mutagène mutagènes mutagenèse mutagénèse mutagénique mutagéniques mutandis mutant mutants mutateur mutatif mutation mutationnel mutationnelles mutations mutatis muté muter mutualisables mutualisant mutualisation mutualisations mutualise mutualisé mutualisée mutualisées mutualisent mutualiser mutualisés mutualisme mutualisons mutualiste mutualistes mutualite mutualité mutuel mutuelle mutuellement mutuelles mutuelliste permutables permutant permutants permutateur permutation permutations permuter phosphoglucomutase rétromutantes surmutation télécommutateurs transmutation transmutée transmutées transmuter transmuterai transmutes transmutés transmuteur transmuteuse transmutez transmutons''',
'es':'''antimutante antimutantes autoconmutador conmutacion conmutación conmutado conmutador conmutar conmutarle conmutarte conmutativo dismutasa inmutabilidad inmutable inmutablemente inmutar inmutarme inmutarse inmutarte intransmutable mutabilidad mutable mutacion mutación mutacional mutado mutador mutadora mutagénesis mutagenica mutagenico mutagénico mutageno mutagenos mutandis mutandonos mutandose mutante mutantito mutar mutaria mutarlo mutarlos mutarnos mutarse mutarte mutatis mutativa mutuables mutual mutualidad mutualismo mutualista mutualizado mutuamente mutuario mutuo nanomutación permuta permutable permutacion permutación permutante permutar permutarle permutarlo premutación retromutageno retromutágeno supermutantes transmutacion transmutación transmutacional transmutador transmutadora transmutadores transmutándose transmutanos transmutante transmutar transmutarla transmutarlos transmutarme transmutarse trasmutar trasmutarlo''',
'it':'''antimutagene antimutagenico antimutageno capomuta commutagli commutare commutargli commutarla commutativa commutative commutativo commutatore commutazione commutera dismutasi dismutazione fosfoglucomutasi immutabile immutabilita immutabilità immutabilmente immutato immutevole mutabile mutabili mutabilità mutaforma mutaforme mutaformismo mutagena mutagene mutagenesi mutageni mutagenica mutagenico mutageno mutamento mutami mutandis mutandola mutandoli mutandomi mutante mutapelle mutare mutargli mutarla mutarlo mutarmi mutarne mutarsi mutarti mutatelo mutativa mutatore mutatori mutavasi mutazionale mutazione mutua mutuabile mutualismo mutualista mutualistico mutualita mutualità mutualizzato mutualizzazione mutuamente mutuare mutuario mutuataria mutuatario mutuazione mutuo permuta permutare permutarle permutatore permutazione permutazioni rimutare ritramutarli sovramutare supermutanti tramutamento tramutandola tramutandomi tramutandosi tramutarci tramutare tramutarla tramutarli tramutarlo tramutarmi tramutarsi tramutarti tramutarvi tramutatasi tramutatelo tramutatevi tramutatosi tramutazione trasmuta trasmutano trasmutante trasmutanti trasmutare trasmutata trasmutate trasmutati trasmutato trasmutatore trasmutatori trasmutazionale trasmutazione trasmutiamo trasmuto trasmutò trasmutore''',
'ru':'''антимутаген коммутативный коммутатор коммутационный коммутация коммутировать коммутируемый коммутирующий мутабельный мутаген мутагенез мутагенный мутант мутантик мутантка мутантный мутанток мутантский мутатор мутаторный мутационный мутация мутировавший мутирование мутированный мутировать мутироваться мыши-мутанты некоммутировать немутировать перекоммутировать пермутация полумутант скоммутироваться субмутант супермутант супермутантка трансмутатор трансмутационный трансмутация трансмутировать''',
'de':'''mutabel mutabilität mutagen mutandis mutant mutante mutanten mutantin mutantinnen mutation mutationen mutatis mutatoren mutier mutieren mutierend mutiert mutualistische kommutativ kommutativgesetz kommutator permutation permutationen transmutation transmutationen transmutieren transmutiert'''}
positive={l:set(s.split()) for l,s in selected.items()}
de_heads=['mutation','mutanten','mutantin','mutagen','mutier','kommutat','permutation','transmutat'];de_withheld=set('''ichnieeinmutant mitmutanten mutant-bike-zeit mutantionen mutationarten muttermutiertes mutations super-normalen-zu-super-mutanten-maschinerie weitraummutantenfiimen'''.split());de_extra=set('''fliegenmutant kojotenmutant meteormutanten scheißmutant scheißmutanten stahlmutant supermutant tiermutation übermutant wassermutantin ziegenmutant'''.split())
retired=['ety:61108b488e06','ety:727be1d24fa1'];langs=list(positive);old=json.load(gzip.open(base/'latin-pairs-checkpoint-20261001/original-families.json.gz','rt'));original={'families':{i:old['families'][i] for i in retired},'members':{l:{i:old['members'][l][i] for i in retired} for l in langs}}
forms={l:['мут'] if l=='ru' else ['mut'] for l in langs};candidates={};decisions={};counts={};german_reviewed=[]
for l in langs:
 by_id={m['lemma_id']:m for m in json.load(gzip.open(base/'next-roots-reflex-checkpoint-20261001'/f'{l}-candidates.json.gz','rt'))['mut']}
 for i in retired:
  for m in original['members'][l][i]:
   if m['lemma_id'] not in by_id:by_id[m['lemma_id']]={**m,'source_family_ids':[i]}
   elif i not in by_id[m['lemma_id']]['source_family_ids']:by_id[m['lemma_id']]['source_family_ids'].append(i)
 ms=sorted(by_id.values(),key=lambda m:(m['word'],m['lemma_id']));candidates[l]={'mut':ms};ds=[]
 for m in ms:
  w=m['word'];f=fold(w);status='uncertain';reason=f'Unconfirmed {l} lexical identity or grammar for {w}; possible personal/place name, foreign quotation, spelling error or phrase fusion. No admission by short mut overlap; context/lexical evidence remains required.'
  de_ok=l=='de' and (any(h in f for h in de_heads) or w in de_extra) and w not in de_withheld
  if w in positive[l] or de_ok:
   status='accepted';reason=f'Explicitly reviewed {l} change/exchange derivative, inflection or transparent compound {w}; recognizable Latin mutare element. Mutual/mutuo derives through mutuus from mutare, supported directly by Merriam-Webster/Treccani, not inferred solely from a remote ancestor.'
   if de_ok:german_reviewed.append(w)
  elif l=='it' and 'mutand' in f:
   reason=f'{w} has a possible clothing/underwear derivative: Treccani confirms mutandae from mutare, but modern association of this specialized branch with international mut requires a separate recognizability/context decision. Historical descent alone does not grant membership.'
  elif any(h in f for h in ['azimut','azimuth','bismut','wismut','азимут','висмут','бисмут']):
   status='excluded';reason=f'{w} has the independent Arabic azimuth/directions or bismuth/Wismut mineral head, not Latin mutare; intact overlapping letters do not merge these lexical roots.'
  elif 'mutil' in f or 'мутилят' in f:
   status='excluded';reason=f'{w} belongs to mutilus/mutilare maiming ancestry, independent of mutare change; semantic injury/change similarity alone is insufficient.'
  elif l in ['en','fr'] and (f.startswith(('mutin','mutine')) or w in ['mutin','mutine','mutiner','mutinerie','mutiny']):
   status='excluded';reason=f'{w} belongs to French meute/mutin and ultimately movere/motus, not mutare; dictionary etymology distinguishes rebellion from the change/exchange element.'
  elif l=='en' and (w in ['mute','muted','mutely','muteness','muting','muter','mutes','deafmute'] or f.startswith(('mutter','mutton','smut','unmute'))):
   status='excluded';reason=f'{w} has an independent silence mutus, muttering, mutton/dog or smut lexical head, not the Latin change/exchange element; preserve independent components.'
  elif l=='fr' and f.startswith(('mutis','mutit','mutiqu')):
   status='excluded';reason=f'{w} belongs to mutus silence and its French derivatives, not muter/mutation from mutare.'
  elif l=='de' and (any(h in f for h in ['mutter','schmutz','gemut','armut','demut','wehmut','wermut','hochmut','mutig','mutlos','mutmass','mutwill','mutprobe','mutmach']) or f in ['mut','mutes','muten','muter']):
   status='excluded';reason=f'{w} has an identifiable native German courage/spirit, mother/nut, poverty, dirt or wormwood head, rather than the borrowed mutieren/mutation element. Native routes remain separate.'
  elif l=='ru' and not any(h in f for h in ['трансмут','мутаци','мутир','мутан','мутаген','мутат','коммут','мутуал']) and (any(h in f for h in ['возмут','баламут','хомут','перламут','смут','мутуз']) or f.startswith(('замут','помут','намут','отмут','мутн','омут')) or w in ['мутить','мутиться','муть','мутно','мутовка']):
   status='excluded';reason=f'{w} has a native Slavic muddy/disturb/collar/pond or borrowed pearl lexical head, independent of international мутация/мутировать; similar Cyrillic spelling does not establish mutare ancestry.'
  elif any(i in m['source_family_ids'] for i in retired) and not any(h in f for h in forms[l]):
   status='excluded';reason=f'{w} has an independent stem inherited through a suffix-expanded mutatio/mutati route; the action suffix supplies no reviewed mut national element.'
  ds.append({'lemma_id':m['lemma_id'],'word':w,'status':status,'reason':reason,'source_family_ids':m['source_family_ids']})
 decisions[l]={'mut':ds};counts[l]={s:sum(d['status']==s for d in ds) for s in ['accepted','excluded','uncertain']}
artifacts={}
for name,value in [('candidates.json.gz',candidates),('original-families.json.gz',original)]:
 raw=gzip.compress(json.dumps(value,ensure_ascii=False,separators=(',',':')).encode(),mtime=0);(out/name).write_bytes(raw);artifacts[name]=hashlib.sha256(raw).hexdigest()
sources=[('https://www.merriam-webster.com/dictionary/azimuth','Arabic al-sumut directions, independent of mutare.'),('https://www.merriam-webster.com/dictionary/bismuth','New Latin bismuthum from German Wismut, independent of mutare.'),('https://www.duden.de/rechtschreibung/mutieren','Borrowed Latin mutare and modern change meanings.'),('https://www.duden.de/rechtschreibung/Mut','Native Middle/Old High German muot, independent of Latin mutare.'),('https://www.duden.de/rechtschreibung/Mutant','German mutant head and morphology.'),('https://www.merriam-webster.com/dictionary/mutual','Explicit mutuus derivation from mutare.'),('https://www.treccani.it/vocabolario/mutuo1/','Explicit mutuus derivation from mutare and exchange meanings.'),('https://www.treccani.it/vocabolario/mutare/','Italian change verb and inflection.'),('https://www.treccani.it/vocabolario/mutazione/','Mutation head.'),('https://dle.rae.es/mutar','Spanish mutare derivative and grammatical forms.'),('https://www.merriam-webster.com/dictionary/mute','Independent mutus silence and separate bird verb.'),('https://www.merriam-webster.com/dictionary/mutiny','Independent movere/motus rebellion ancestry.'),('https://www.dictionnaire-academie.fr/article/A9M3294','Mutin derives from meute, not mutare.'),('https://www.treccani.it/vocabolario/mutilare/','Independent mutilus maiming head.'),('https://www.treccani.it/vocabolario/mutande/','Historical mutandae clothing branch; modern recognizability held for further review.'),('https://gramota.ru/storage/public/normdicts/slovar_inostr_slov.pdf','Explicit Russian mutant/mutation from Latin muto/mutatio.')]
result={'canonical_roots':['mut'],'surface_forms':{'mut':forms},'decisions':decisions,'counts':counts,'source_artifacts':artifacts,'sources':[{'url':u,'supports':s} for u,s in sources],'limitations':['Saved linguistic review only, not a runtime mutation.','Clothing descendants are not admitted on ancestry alone; modern recognizability needs further adjudication.','Unconfirmed homographic muto/muta or named tokens are withheld rather than given invented sense frequencies.','Productive grammar/head evidence does not claim a dictionary entry for every compound.']}
(out/'linguistic-decisions.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');(out/'explicit-positive-selections.json').write_text(json.dumps({l:sorted(ws) for l,ws in positive.items()},ensure_ascii=False,indent=2)+'\n');(out/'german-reviewed-positive-words.json').write_text(json.dumps(german_reviewed,ensure_ascii=False,indent=2)+'\n');(out/'inventory.json').write_text(json.dumps({'retired_families':retired,'artifacts':artifacts,'counts':counts,'runtime_applied':False},indent=2)+'\n');print(json.dumps(counts))
