"""Saved-candidate review of recognizable work/operation/opera element; no runtime mutation."""
import json,gzip,hashlib,re,unicodedata
from pathlib import Path
base=Path('audit/associative-family-v5');out=base/'operation-checkpoint-20261001';out.mkdir(exist_ok=True)
fold=lambda w: ''.join(c for c in unicodedata.normalize('NFKD',w.lower()) if not unicodedata.combining(c))
selected={
'en':'''battery-operated co-operate co-operation co-operative co-operatively co-operatives co-operator coin-operate cooperate cooperation cooperational cooperative cooperatively cooperativeness cooperatives cooperativism cooperativist cooperativity cooperator cyberoperations deoperational hand-operated inoperable inoperate inoperational inoperative inter-operability interoperability interoperable interoperate interoperating interoperation interoperative intra-operative intraoperational intraoperative intraoperatively non-cooperation non-cooperative non-operating non-operational non-operative noncooperation noncooperative nonoperating nonoperational opera operability operable operand operandi operant operas operate operated operates operatic operatically operatics operating operation operational operationalisation operationalise operationalised operationalising operationalization operationalize operationally operationals operations operative operatively operativeness operatives operator operators operatory operetta operettary operon operose peri-operative perioperative post-operative post-operatively postoperative postoperatively pre-operative pre-operatively preoperational preoperative preoperatively recooperate recooperation reoperate reoperation soap-opera soapopera telecooperation teleoperated teleoperator unco-operative uncooperated uncooperating uncooperation uncooperative unoperate unoperated''',
'fr':'''câblo-opérateur câblo-opérateurs chef-opérateur cooperant coopérant coopérateur cooperatif coopératif cooperation coopération coopérations coopératisme cooperative coopérative coopérativement coopératives coopere coopère coopérée cooperent coopèrent cooperer coopérer coopèrera coopererai coopèrerai coopèrerais coopèrerait coopèreras coopererez coopèrerez coopèreriez coopèrerons coopereront coopèreront cooperes coopères coopérés cooperez cooperiez cyberopérations inoperable inopérable inopérant inopérationnel inopérationnelle inopérationnels interopérabilité interopérable interopérables intraopérative opera opéra opéra-bouffe opéra-comique opéra-théâtre opérabilité opérable opérables operaient operait opérande operandi opérandi operant opérant operante opérante opérants operas opéras operateur opérateur operateurs opérateurs opératif opératifs operation opération opérationnalisation opérationnaliser opérationnalité operationnel opérationnel operationnelle opérationnelle opérationnellement operationnels opérationnels operations opérations opératique opératiques opérative opérativement opératives operatoire opératoire operé opéré operee operent operer opérer operera opererait opereriez operes operetta opérette operez opéristique opéron operons périopératoire postopératoire préopératoire''',
'es':'''antioperaciones ciberoperativo cooperacion cooperación cooperado cooperador cooperais cooperante cooperar cooperaramos cooperarian cooperarle cooperarnos cooperativa cooperativamente cooperatividad cooperativismo cooperativista cooperativo coopereis exoperativo incooperativo inoperable inoperacional inoperancia inoperante inoperativo interoperabilidad interoperativa interoperatividad intraoperativa intraoperativo intraoperativos intraoperatoria intraoperatoriamente intraoperatorias intraoperatorio megaoperación miniópera multioperacional opera ópera operábais operabamos operable operacion operación operacionables operacional operacionalmente operacioncita operadle operado operador operadora operais opérala operalas opérale operalo opéralo operame opérame operandi operandola operándola operándolas operandole operándole operándoles operándolo operandolos operándolos operándome operandose operándose operándote operante operar operaria operario operarla operarlas operarle operarles operarlo operarlos operarme operármela operármelas operármelo operármelos operarnos operaros operarse operarsela operársela operarselo operarte operártelas operártelo operás operate opérate operática operáticas operático operáticos operativamente operatividad operativo operatoria operatorio operatriz opérela opérele opérelo opéreme operémosla operemoslo opérenla opérenlo opérese opereta operistica operístico perioperatoria posoperación posoperacional posoperatoria posoperatorias posoperatorio posoperatorios postoperado postoperativo postoperatoria postoperatorio preoperación preoperacional preoperaciones preoperada preoperado preoperativo preoperatoria preoperatorias preoperatorio preoperatorios radiooperador reoperación reoperado reoperar semioperativa semioperativas teleoperador teleoperadora teleoperadoras teleoperadores touroperador turoperador''',
'it':'''adoperala adoperandosi adoperarci adoperare adoperarla adoperarle adoperarli adoperarlo adoperarmi adoperarne adoperarsi adoperarti adoperarvi adoperera adoperero antioperaio cineoperatore cineoperatrice co-operativo cooperante cooperare cooperativa cooperativamente cooperativismo cooperativistico cooperatività cooperativo cooperatore cooperazione cooperera cooperero grand-opéra inoperabile inoperabili inoperabilita inoperante inoperanti inoperativa inoperative inoperativi inoperatività inoperativo inoperosita inoperosità inoperoso interoperabile interoperabilita interoperabilità interoperare interoperatività intraoperativa intraoperatori intraoperatoria intraoperatorie intraoperatorio manodopera maxioperazione non-cooperazione opera operabile operabilità operaia operaiaccio operaio operaismo operaista operalo operami operandi operando operandola operandolo operandomi operante operarci operare operargli operarla operarle operarli operarlo operarmi operarne operarsi operarti operarvi operatela operatelo operatemi operativamente operativita operatività operativo operato operatore operatorio operatosi operatrice operazionale operazionali operazioncina operazione opere operera operero operetta operiamolo operina operista operistico operon operone operosissimo operosita operosità operoso post-operativo post-operatorio postoperativo postoperatori postoperatoria postoperatorie postoperatorio postoperazione pratico-operativo pre-operatorio preoperativi preoperatori preoperatoria preoperatorie preoperatorio radiooperatore radiooperatori recooperare riopera rioperano rioperare rioperarla rioperarmi rioperarti rioperato rioperiamo scioperante scioperare scioperato scioperetto sciopero scioperuncolo soap-opera tecnico-operativo telecineoperatore teleoperatore tour-operator''',
'ru':'''авиаоперация автооператор антиопера антиоперация антитеррористическаяоперация артоперация банкооператор видеооператор госоперация гранд-опера дооперационный дооперировать звукооператор интраоперативный интраоперационный кардиооперация кассира-операциониста кибероперация кинооператор кинооператорша контроперация кооператив кооперативный кооператор кооперационный кооперация кооперирование кооперированный кооперировать кооперироваться космоопера метрополитен-опера микрооперация мыльнооперный неоперабельность неоперабельный неоперативный неоперировать опер опера операбельность операбельный операнд операнда операнди оперантный оператив оператива оперативка оперативнее оперативненький оперативненько оперативник оперативница оперативничка оперативно оперативно-розыскная оперативно-розыскного оперативно-розыскной оперативно-розыскную оперативно-розыскные оперативно-розыскных оперативно-следственная оперативно-служебной оперативно-стратегических оперативно-тактические оперативно-тактических оперативно-тактического оперативно-тактической оперативность оперативный оперативщик оператор оператор-постановщик операторный операторский операторша операторщик операции операций операционализация операциональный операционист операционистка операционка операционная операционный операция опербаза оперблок опергруппа оперирование оперированный оперировать оперироваться оперирующий оперетка опереточный оперетта оперетту оперетты оперный оперолюба оперотдел оперотряд оперпункт оперработник оперсводка оперсотрудник оперуполномоченный оперцентр оперштаб пикооперация пооперировать послеоперационный постоперационный потребкооперация предоперационный преоперационный преоперировать промкооперация прооперированный прооперировать прооперироваться радиооператор радиооперация разведоперация рок-опера рок-опере рок-оперу рок-оперы сельхозкооператив скооперировать скооперироваться следственно-оперативная следственно-оперативной спецоперативник спецоперация светооператор телеопера телеоператор техоператор туроператор туроператорский''',
'de':'''oper opera operaismus operand operanden operandi operant operante operanten operateur operateure operateuren operchen operintendantin operkenner operlippe staatsoper volksoper semperoper interoperabilität interoperabel'''}
positive={l:set(s.split()) for l,s in selected.items()}
# Reviewed productive German compounds: an intact dictionary head, valid noun
# boundaries and inflection, with malformed/fused occurrences withheld explicitly.
german_heads=['operation','operativ','operator','operateur','operier','operabel','operabil','kooperat','kooperier','opern','operett']
withheld=set('''aufopernde dieoperation gehinroperation geheimoperations inklusiveaugenoperation kooperationbereitschaft kooperations kooperationsabkomme loopern miiitäroperation operationsaal operationsrauml operettn operierunden opernaus wirbelsäurenoperation'''.split())
retired=['ety:58143b06b35a','ety:8ef5f06ceb40'];langs=list(positive);old=json.load(gzip.open(base/'latin-pairs-checkpoint-20261001/original-families.json.gz','rt'))
original={'families':{i:old['families'][i] for i in retired},'members':{l:{i:old['members'][l][i] for i in retired} for l in langs}}
forms={l:['опер'] if l=='ru' else ['oper'] for l in langs};candidates={};decisions={};counts={};german_reviewed=[]
for l in langs:
 by_id={m['lemma_id']:m for m in json.load(gzip.open(base/'next-roots-reflex-checkpoint-20261001'/f'{l}-candidates.json.gz','rt'))['oper']}
 for i in retired:
  for m in original['members'][l][i]:
   if m['lemma_id'] not in by_id:by_id[m['lemma_id']]={**m,'source_family_ids':[i]}
   elif i not in by_id[m['lemma_id']]['source_family_ids']:by_id[m['lemma_id']]['source_family_ids'].append(i)
 ms=sorted(by_id.values(),key=lambda m:(m['word'],m['lemma_id']));candidates[l]={'oper':ms};ds=[]
 for m in ms:
  w=m['word'];f=fold(w);status='uncertain';reason=f'Unconfirmed lexical identity, spelling or compound boundary for {l} token {w}; possible proper name, foreign quotation, malformed inflection or phrase fusion. Withheld pending context/lexical evidence.'
  de_ok=l=='de' and any(h in f for h in german_heads) and not any(h in f for h in ['kopern','copern']) and w not in withheld
  if w in positive[l] or de_ok:
   status='accepted';reason=f'Reviewed {l} work/action/operation or opera derivative, inflection or transparent compound {w}; Latin opera/operari element is recognizable, including cooperative, operative and musical-work branches.'
   if l=='it' and 'scioper' in f:reason=f'Italian {w} has the attested ex+opera cessation-of-work branch (Treccani scioperare), with a transparent oper element; not an unrelated substring.'
   if de_ok:german_reviewed.append(w)
  elif any(h in f for h in ['copernic','kopernik','коперник']):
   status='excluded';reason=f'{w} is derived from the proper name Copernicus/Kopernik, not Latin opera/operari; retain its independent name/scientific routes.'
  elif l=='de' and f.startswith('opera-'):
   status='excluded';reason=f'{w} is explicitly a browser/product-name compound around Opera, without a common operation/opera lexical analysis; no guessed sense frequency is split.'
  elif any(h in f for h in ['opercu','opercol','оперкул']) or (l=='it' and any(h in f for h in ['coperchi','copert'])):
   status='excluded';reason=f'{w} belongs to Latin operire/cooperire covering/lid ancestry, independent of opera/operari work; similar spelling does not merge these Latin etymons.'
  elif any(h in f for h in ['pericard','pericarde','peritone','peroxid','perossid','perfusion','perfus','перикард','перитон','перокси','перфуз']):
   status='excluded';reason=f'{w} contains an independent peri/perfuse/peroxide medical or chemical element after a combining vowel; o+per across the boundary is not opera/operari.'
  elif l=='en' and (f.startswith(('proper','improper','developer','redeveloper')) or w in ['cooper','coopers','cooperage','coopered','coopering']):
   status='excluded';reason=f'{w} has a separate proprius/proper, develop or barrel-maker cooper lexical stem, not the reviewed operation element; derivative endings do not create oper.'
  elif l in ['it','es'] and f in ['improperio','impropero']:
   status='excluded';reason=f'{w} belongs to the improperium/improperare reproach branch rather than work/operation; dictionary etymology distinguishes these heads.'
  elif l=='fr' and (f.startswith(('galop','saloper','ecop','chop','develop','devellop','envellop')) or f.startswith(('neoperon','neoperon'))):
   status='excluded';reason=f'{w} has an independent gallop/filth/bailing/grabbing/develop/envelop or Peron-name stem; apparent oper is a boundary or unrelated spelling.'
  elif l=='ru' and (any(h in f for h in ['перевоз','передач','передат','перераб','перенос','перевод','персона','период']) or f.startswith(('опереж','оперед','оперен','оперени','оперенн','оперь','оперить','опериться','опереть','опереться','оперест','попер','сопер','допер','пропереть','проперд','проперч','проперти','неоперив','неоперить','неопериться'))):
   status='excluded';reason=f'{w} has an identifiable native feather/support/outrun/rival or пере-/пер- compound branch, not borrowed opera/operari. Exact Cyrillic overlap is insufficient.'
  elif any(i in m['source_family_ids'] for i in retired) and not any(h in f for h in forms[l]):
   status='excluded';reason=f'{w} was inherited through a suffix-expanded operatio/operati route; independent lexical stem and action ending provide no reviewed national oper element.'
  ds.append({'lemma_id':m['lemma_id'],'word':w,'status':status,'reason':reason,'source_family_ids':m['source_family_ids']})
 decisions[l]={'oper':ds};counts[l]={s:sum(d['status']==s for d in ds) for s in ['accepted','excluded','uncertain']}
artifacts={}
for name,value in [('candidates.json.gz',candidates),('original-families.json.gz',original)]:
 raw=gzip.compress(json.dumps(value,ensure_ascii=False,separators=(',',':')).encode(),mtime=0);(out/name).write_bytes(raw);artifacts[name]=hashlib.sha256(raw).hexdigest()
sources=[('https://www.duden.de/rechtschreibung/operieren','Latin operari and operation/action meanings.'),('https://www.duden.de/rechtschreibung/Oper','Opera as a Latin opera work-derived musical head.'),('https://www.treccani.it/vocabolario/operare/','Italian work/action verb and grammar.'),('https://www.treccani.it/vocabolario/opera/','Work and musical-work noun.'),('https://www.treccani.it/vocabolario/scioperare/','Ex+opera cessation-of-work derivative.'),('https://dle.rae.es/operar','Spanish operation verb and inflection.'),('https://www.merriam-webster.com/dictionary/operate','English operation head.'),('https://www.merriam-webster.com/dictionary/operon','French operer-derived gene term, not an unrelated medical etymon.'),('https://www.merriam-webster.com/dictionary/cooper','Independent barrel-maker head.'),('https://www.treccani.it/vocabolario/opercolo/','Independent covering/lid operire ancestry.'),('https://www.treccani.it/vocabolario/improperio/','Independent reproach head.'),('https://www.dictionnaire-academie.fr/article/A9O0521','French operari-derived verb.'),('https://www.dictionnaire-academie.fr/article/A9C4137','Cooperation verb and accepted 1990 future spellings.'),('https://www.dictionnaire-academie.fr/article/A9M2479','Conventional modus operandi phrase.'),('https://gramota.ru/meta/operirovat','Russian operation/action head.'),('https://gramota.ru/poisk?mode=slovari&query=%D1%82%D0%BE%D0%BB%D0%B5%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C','Indexed explicit Latin operari source for Russian оперировать.')]
result={'canonical_roots':['oper'],'surface_forms':{'oper':forms},'decisions':decisions,'counts':counts,'source_artifacts':artifacts,'sources':[{'url':u,'supports':s} for u,s in sources],'limitations':['Saved linguistic review only; no operation runtime family is applied by this script.','Source measurements aggregate word forms; homographic lexical/name senses are not assigned invented separate frequencies.','Unconfirmed corpus tokens remain withheld, not declared certified dictionary entries.','Productive compounds have explicit head and grammatical analysis; not every compound has its own dictionary article.']}
(out/'linguistic-decisions.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');(out/'explicit-positive-selections.json').write_text(json.dumps({l:sorted(ws) for l,ws in positive.items()},ensure_ascii=False,indent=2)+'\n');(out/'german-reviewed-positive-words.json').write_text(json.dumps(german_reviewed,ensure_ascii=False,indent=2)+'\n');(out/'inventory.json').write_text(json.dumps({'retired_families':retired,'artifacts':artifacts,'counts':counts,'runtime_applied':False},indent=2)+'\n');print(json.dumps(counts))
