"""Full saved-candidate disposition review of the relation/report/relative element."""
import json,gzip,hashlib,unicodedata,re
from pathlib import Path
base=Path('audit/associative-family-v5');out=base/'relation-checkpoint-20261001';out.mkdir(exist_ok=True)
fold=lambda w: ''.join(c for c in unicodedata.normalize('NFKD',w.lower()) if not unicodedata.combining(c))
# Explicit source spellings, including productive grammar, reviewed together.
selected={
'en':'''autocorrelation correlate correlated correlater correlates correlation correlational correlations correlative correlator cross-correlation inter-relate inter-related inter-relation inter-relations inter-relationship inter-relationships intercorrelated intercorrelation interrelate interrelatedness interrelation interrelationship irrelatively miscorrelation non-related non-relativistic nonrelated nonrelationship nonrelative relatability relatable relatables relatably relate relateable related relatedly relatedness relater relates relating relation relational relationality relationally relationals relationary relations relationship relationship-building relationships relativeness relative relatively relatives relativise relativism relativist relativistic relativistically relativity relativize relator relatory relatum uncorrelate uncorrelated unrelatable unrelateable unrelated''',
'de':'''anfrage-auftrags-relation aufwand-nutzen-relation bedingungs-ereignis-relationen benutzerrelation berufskorrelation betreuungsrelation betreuungsrelationen bilanzrelationen customer-relationship-management dispersionsrelationen distanzrelationen enthaltensein-relation hauptrelation hauptwegerelationen investor-relations-agenturen investor-relations-sites korrelat korrelate korrelation korrelationen korrelationsanalyse korrelationsformel korrelationskoeffizient korrelationskoeffizienten korrelationsmatrix korrelationstabellen korrelationsverhalten korrelativ korrelativen korrelator kosten-nutzen-relation kosten-nutzenrelation kulturrelativismus kulturrelativistisch makrorelationen nerode-relation phänotyp-genotyp-korrelation public-relations-kampagne public-relations-remmidemmi publicrelations rangkorrelation relation relational relationale relationalen relationaler relationales relationalität relationen relationenschemata relations relations-aktivitäten relationsbegriff relationship-management-lösungen relativ relativbewegungen relative relativgeschwindigkeit relativiere relativieren relativierend relativierende relativierenden relativierst relativiert relativierung relativismus relativist relativisten relativistisch relativistische relativistischen relativistischer relativistisches relativität relativitäts-theorie relativitätsgesetz relativitätsphysik relativitätsprinzip relativitätstheorie relativitätstheorien relativpronomen relativsatz relativsätze relator schüler-lehrer-relation signalkorrelationsspuren sonnenflecken-relativzahlen stoff-wirkungsrelation unschärferelation werberelationsagenturen''',
'fr':'''autocorrélation corrélat corrélateur corrélatif correlation corrélation corrélativement inter-relations interrelation relater relateurs relatif relatifs relation relationalité relationnées relationnel relationnelle relationner relationniste relations relative relativement relatives relativisation relativiser relativisme relativiste relativistes relativite relativité rétrorelation''',
'es':'''correlativamente correlatividad correlativo correlato relatadlos relatado relatador relátala relátalo relátame relatándole relatándoles relatándosela relatándote relátanos relatar relatarian relatarla relatarlas relatarle relatarles relatarlo relatarlos relatarme relatarnos relatárnoslo relataros relatarsela relatarte reláteme relátemelo relátenme relátenos relativamente relatividad relativismo relativista relativística relativisticas relativisticos relativizar relativo relato relator relatora relatoría relatorio relatorios autocorrelación biorelacionados correlacion correlación correlacional correlacionar correlacionarlas correlacionarse correlaciónelos exrelaciones interrelación interrelacionar interrelacionarnos interrelacionarse irrelacionado postrelaciones publirrelacionista relacion relación relacionabamos relacionable relacionables relacionadamente relacionado relacionador relacionadora relacionadores relacionais relacional relaciónala relaciónalas relaciónale relaciónalo relacionalos relacionamiento relacionamientos relacionándola relacionándole relacionándolo relacionandolos relacionándolos relacionandome relacionándome relacionandonos relacionándonos relacionándoos relacionándose relacionandote relacionándote relacionaos relacionar relacionaria relacionarian relacionarla relacionarlas relacionarle relacionarlo relacionarlos relacionarme relacionarnos relacionaros relacionarse relacionársele relacionarte relacionate relaciónate relacione relacioneis relaciónelo relaciónelos relacionémolos relacionémonos relaciónenlo relacionense relaciónense relaciónese relacionista relacionistas semirrelación''',
'it':'''affettivo-relazionare alcolcorrelato autocorrelazione controrelatore correlativamente correlativo correlatore correlazione interrelato interrelazionale interrelazione irrelato neorelatività presidente-relatore relata relativamente relativismo relativista relativiste relativisti relativistico relativita relatività relativizzare relativizzazione relativo relato relatore relatrice relazionabile relazionabilita relazionale relazionali relazionalità relazionamento relazionandoli relazionandomi relazionarci relazionare relazionarla relazionarle relazionarlo relazionarmi relazionarmici relazionarsi relazionarti relazionartici relazionarvi relazionatemi relazioncina relazione scorrelato socio-relazionare''',
'ru':'''автокоррелятор автокорреляция коррелят коррелятивный корреляционный корреляция нерелятивистский постнеорелятивизм релятивизм релятивист релятивистский релятивность релятивный реляционный реляция'''}
positive={l:set(s.split()) for l,s in selected.items()}
# Full -related compounds have a transparent grammatical boundary; fused phrases
# such as 'aboutourrelationship' do not pass this rule.
langs=list(positive);retired=['ety:474b418e1004','ety:dd07667af787'];old=json.load(gzip.open(base/'latin-pairs-checkpoint-20261001/original-families.json.gz','rt'))
original={'families':{i:old['families'][i] for i in retired},'members':{l:{i:old['members'][l][i] for i in retired} for l in langs}}
forms={'en':['relat'],'de':['relat'],'fr':['relat'],'es':['relat','relac'],'it':['relat','relaz'],'ru':['релят','реляц']};candidates={};decisions={};counts={}
for l in langs:
 by_id={m['lemma_id']:m for m in json.load(gzip.open(base/'next-roots-relation-reflex-checkpoint-20261001'/f'{l}-candidates.json.gz','rt'))['relat']}
 for i in retired:
  for m in original['members'][l][i]:
   if m['lemma_id'] not in by_id:by_id[m['lemma_id']]={**m,'source_family_ids':[i]}
   elif i not in by_id[m['lemma_id']]['source_family_ids']:by_id[m['lemma_id']]['source_family_ids'].append(i)
 ms=sorted(by_id.values(),key=lambda m:(m['word'],m['lemma_id']));candidates[l]={'relat':ms};ds=[]
 for m in ms:
  w=m['word'];f=fold(w);status='uncertain';reason=f'Unconfirmed {l} lexical identity or grammar for {w}: possible typo, phrase fusion, foreign quotation or proper name; withheld pending evidence rather than admitted by overlap.'
  transparent=l=='en' and re.fullmatch(r'[a-z]+(?:-[a-z]+)*-related',w)
  if w in positive[l] or transparent:
   status='accepted';reason=f'Explicitly reviewed {l} relation/report/relative derivative, inflection or transparent compound {w}; declared national form preserves the recognizable Latin relatio/relatus element.'
  elif l=='fr' and w in ['frelater','frelaté']:
   status='excluded';reason=f'{w} has French frelater (Middle Dutch verlaten, to decant/adulterate) ancestry, independent of Latin relatio; copied or inflected national forms do not change the lexical branch.'
  elif f.startswith(('prelat','prelac')) or f.startswith(('прелат','прелач')):
   status='excluded';reason=f'{w} belongs to praelatus/praeferre or its ecclesiastical/precedence derivatives; prae+lat is a different prefixed stem from re+lat, despite overlapping letters and remote ferre ancestry.'
  elif l=='es' and (f.startswith(('entrelaz','desentrelaz','entrelac','desentrelac','abrelata','cubrelata'))):
   status='excluded';reason=f'{w} is an independent lazo/lata lexical branch across a prefix/compound boundary, not the relatio/relatus element. Similar meaning alone does not merge associative families.'
  elif l=='fr' and ('entrelac' in f or 'relach' in f or f.startswith('relacer')):
   status='excluded';reason=f'{w} belongs to lacer/lacs or relacher release (relaxare), independent of relation/relatio; the overlapping relac retrieval spelling is not a French reflex of relat.'
  elif l=='ru' and any(s in f for s in ['стрел','перелаз','перелат','перелач']):
   status='excluded';reason=f'{w} has native shooting/climbing/patching or phrase-boundary spelling, independent of реляция/релятивный; transliterated overlap does not imply Latin relation ancestry.'
  elif any(i in m['source_family_ids'] for i in retired) and not any(s in f for s in forms[l]):
   status='excluded';reason=f'{w} was inherited through a suffix-expanded relatio/relati container but has an independent stem without the reviewed associative element; preserve its other lexical routes.'
  ds.append({'lemma_id':m['lemma_id'],'word':w,'status':status,'reason':reason,'source_family_ids':m['source_family_ids']})
 decisions[l]={'relat':ds};counts[l]={s:sum(d['status']==s for d in ds) for s in ['accepted','excluded','uncertain']}
artifacts={}
for name,value in [('candidates.json.gz',candidates),('original-families.json.gz',original)]:
 raw=gzip.compress(json.dumps(value,ensure_ascii=False,separators=(',',':')).encode(),mtime=0);(out/name).write_bytes(raw);artifacts[name]=hashlib.sha256(raw).hexdigest()
sources=[('https://www.merriam-webster.com/dictionary/relate','Latin relatus/referre and modern report/connection senses.'),('https://www.duden.de/rechtschreibung/Relation','Latin relatio, modern connection/report heads.'),('https://www.duden.de/rechtschreibung/relativ','Latin relativus and relatum; productive relative derivatives.'),('https://www.dictionnaire-academie.fr/article/A9R1460','French relation from Latin relatio/referre.'),('https://www.treccani.it/vocabolario/relazione/','Italian relatio/relatus reflex and modern senses.'),('https://www.treccani.it/vocabolario/correlazione/','Transparent Italian correlation derivative.'),('https://dle.rae.es/relación','Spanish noun from Latin relatio.'),('https://dle.rae.es/relacionar','Spanish derivative and grammatical conjugation.'),('https://dle.rae.es/relatar','Spanish report verb and inflection.'),('https://dle.rae.es/relativo','Relative derivative.'),('https://gramota.ru/meta/relyatsiya','Russian report noun definition; page indexed but direct fetch blocked.'),('https://gramota.ru/poisk?dicts%5B0%5D=42&mode=slovari&query=%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9&simple=0','Russian relational adjective and explicit Latin relativus source.'),('https://gramota.ru/meta/korrelyativnyy','Russian correlative head and standard inflection.'),('https://www.dictionnaire-academie.fr/article/A9R1451','Independent French release head.'),('https://www.larousse.fr/dictionnaires/college/rel%C3%A2cher/34284','Independent relaxare etymology.'),('https://www.dictionnaire-academie.fr/article/A9F1609','French frelater from Middle Dutch verlaten.'),('https://www.merriam-webster.com/dictionary/prelate','Separate prelate head.'),('https://www.oed.com/dictionary/prelate_v1','Praelat/praeferre etymons.'),('https://dle.rae.es/entrelazar','Independent intertwining verb and inflection.'),('https://dle.rae.es/lata','Independent lata material/container etymon.')]
result={'canonical_roots':['relat'],'surface_forms':{'relat':forms},'decisions':decisions,'counts':counts,'source_artifacts':artifacts,'sources':[{'url':u,'supports':s} for u,s in sources],'limitations':['This is a saved linguistic review, not an applied runtime family.','Uncertain corpus spellings remain withheld; productive heads and grammar do not certify malformed or foreign tokens.','Lexical dictionary head evidence does not claim a dictionary article for every compound.','No invented corpus frequencies or sense-level measurements.']}
(out/'linguistic-decisions.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');(out/'explicit-positive-selections.json').write_text(json.dumps({l:sorted(ws) for l,ws in positive.items()},ensure_ascii=False,indent=2)+'\n');(out/'inventory.json').write_text(json.dumps({'retired_families':retired,'artifacts':artifacts,'counts':counts,'runtime_applied':False},indent=2)+'\n');print(json.dumps(counts))
