const API_BASE = location.hostname === 'landquart.github.io' ? 'https://interal.vercel.app' : '';
const CARD_SECTION = 'altervordes';
const CARD_PREFIX = 'al_';
const PROCEDURES = [
  ['grammaticalShortWords','Слово не является грамматическим или кратким служебным элементом.'],
  ['internationalisms','Слово не является интернационализмом.'],
  ['communityWords','Слово не является словом профессионального, культурного, социального или субкультурного сообщества.'],
  ['indoEuropeanWords','Слово не проходит процедуру общих индоевропейских слов.'],
  ['associativeWords','Слово не проходит процедуру ассоциативных слов.']
];
const CONTROL = [['en','English'],['de','Deutsch'],['fr','Français'],['es','Español'],['it','Italiano'],['ru','Русский'],['el','Ελληνικά']];
const AUX = [['pl','Polski'],['sv','Svenska'],['ca','Català'],['oc','Occitan'],['ro','Română']];
const REF = [['la','Latina'],['sa','Sanskrit'],['lt','Lietuvių']];
const CRITERIA = [['brevity','B — brevity / краткость',.15],['pronounceability','P — pronounceability / произносимость',.20],['conflictAbsence','C — conflict absence / отсутствие конфликтов',.25],['derivationalPotential','D — derivational potential / деривационный потенциал',.20],['neutrality','N — neutrality / нейтральность',.10],['residualRecognizability','R — residual recognizability / остаточная узнаваемость',.10]];

const UI_TEXT = {
  ru: {
    eyebrow: 'Иные слова', lead: 'Alter vordes — инструмент для слов, которые не проходят ни одну из пяти основных процедур отбора. В этом случае форма выбирается вручную по дополнительным критериям: краткости, произносимости, отсутствию конфликтов и возможности будущей деривации.', notice: 'Эта процедура применяется только тогда, когда слово не проходит пять основных типов. Результат является формализованным ручным выбором, а не автоматическим доказательством международности.', basic: 'Основные данные', candidate: 'Кандидатная форма Интераля', meaning: 'Значение слова', russian: 'Русский перевод', pos: 'Часть речи', comment: 'Комментарий/пояснение', failedTitle: 'Проверка провала пяти процедур', warn: 'Alter vordes применяется только после проверки пяти основных процедур.', ok: 'Пять основных процедур отмечены как проверенные и неприменимые.', control: 'Контрольные языки', aux: 'Вспомогательные языки', ref: 'Справочные языки', altTitle: 'Альтернативные формы', add: 'Добавить форму', derivativesTitle: 'Возможные дериваты', calculate: 'Calcular', ai: 'AI evaluation', json: 'Crear JSON', copyJson: 'Copiar JSON', download: 'Descargar JSON', link: 'Copiar link', result: 'Результат', human: 'Финальное решение принимает человек.', jsonCard: 'JSON-карточка', form: 'Форма', word: 'Слово/эквивалент', ipa: 'IPA или произношение', etymology: 'Этимологический комментарий', langComment: 'Комментарий', remove: 'Удалить', best: 'Лучшая форма', alternatives: 'Альтернативы', risks: 'Риски', derivatives: 'Дериваты', aiUnavailable: 'AI недоступен, ручной режим продолжает работать.', validationCandidate: 'candidate is required', validationMeaning: 'meaning is required', validationProcedures: 'failedProcedures must contain all five checks', procedures: { grammaticalShortWords: 'Слово не является грамматическим или кратким служебным элементом.', internationalisms: 'Слово не является интернационализмом.', communityWords: 'Слово не является словом профессионального, культурного, социального или субкультурного сообщества.', indoEuropeanWords: 'Слово не проходит процедуру общих индоевропейских слов.', associativeWords: 'Слово не проходит процедуру ассоциативных слов.' }, criteria: { brevity: 'B — brevity / краткость', pronounceability: 'P — pronounceability / произносимость', conflictAbsence: 'C — conflict absence / отсутствие конфликтов', derivationalPotential: 'D — derivational potential / деривационный потенциал', neutrality: 'N — neutrality / нейтральность', residualRecognizability: 'R — residual recognizability / остаточная узнаваемость' } },
  en: {
    eyebrow: 'Other words', lead: 'Alter vordes is a tool for words that do not pass any of the five main selection procedures. In this case, the form is selected manually by additional criteria: brevity, pronounceability, absence of conflicts, and future derivational potential.', notice: 'This procedure is used only after the five main types have been checked. The result is a formalized manual selection, not automatic proof of internationality.', basic: 'Basic data', candidate: 'Interal candidate form', meaning: 'Meaning', russian: 'Russian translation', pos: 'Part of speech', comment: 'Comment / explanation', failedTitle: 'Failure check for five procedures', warn: 'Alter vordes is applied only after checking the five main procedures.', ok: 'The five main procedures are marked as checked and not applicable.', control: 'Control languages', aux: 'Auxiliary languages', ref: 'Reference languages', altTitle: 'Alternative forms', add: 'Add form', derivativesTitle: 'Possible derivatives', calculate: 'Calculate', ai: 'AI evaluation', json: 'Create JSON', copyJson: 'Copy JSON', download: 'Download JSON', link: 'Copy link', result: 'Result', human: 'The final decision is made by a human.', jsonCard: 'JSON card', form: 'Form', word: 'Word/equivalent', ipa: 'IPA or pronunciation', etymology: 'Etymological comment', langComment: 'Comment', remove: 'Remove', best: 'Best form', alternatives: 'Alternatives', risks: 'Risks', derivatives: 'Derivatives', aiUnavailable: 'AI is unavailable; manual mode remains available.', validationCandidate: 'candidate is required', validationMeaning: 'meaning is required', validationProcedures: 'failedProcedures must contain all five checks', procedures: { grammaticalShortWords: 'The word is not a grammatical or short function element.', internationalisms: 'The word is not an internationalism.', communityWords: 'The word is not a professional, cultural, social, or subcultural community word.', indoEuropeanWords: 'The word does not pass the common Indo-European word procedure.', associativeWords: 'The word does not pass the associative word procedure.' }, criteria: { brevity: 'B — brevity', pronounceability: 'P — pronounceability', conflictAbsence: 'C — conflict absence', derivationalPotential: 'D — derivational potential', neutrality: 'N — neutrality', residualRecognizability: 'R — residual recognizability' } }
};
function currentLang(){return localStorage.getItem('interal.lang') === 'en' ? 'en' : 'ru'}
function tr(key){return key.split('.').reduce((o,k)=>o?.[k], UI_TEXT[currentLang()]) ?? key}
function criterionLabel(k){return UI_TEXT[currentLang()].criteria[k] || k}

let lastResult = null;
let lastCard = null;
const $ = (id)=>document.getElementById(id);
const esc = (s)=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const num = (v)=>Math.max(0,Math.min(100,Number(v)||0));
function score(sc){return Math.round(CRITERIA.reduce((sum,[k,,w])=>sum+w*num(sc[k]),0)*10)/10}
function uuid12(){const a='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';return Array.from(crypto.getRandomValues(new Uint8Array(12)),b=>a[b%a.length]).join('')}
function renderLang(container, list, hasIpa, ref=false){$(container).innerHTML=list.map(([c,n])=>`<div class="lang-card"><h3>${n}</h3><input class="interal-input" id="${container}_${c}_word" placeholder="${ref?tr('form'):tr('word')}">${hasIpa?`<input class="interal-input" id="${container}_${c}_ipa" placeholder="${tr('ipa')}">`:''}<textarea class="interal-textarea" id="${container}_${c}_comment" placeholder="${ref?tr('etymology'):tr('langComment')}"></textarea></div>`).join('')}
function renderProcedures(){ $('failedBox').innerHTML=PROCEDURES.map(([k])=>`<label class="check"><input type="checkbox" id="fp_${k}"><span>${tr('procedures.'+k)}</span></label>`).join(''); PROCEDURES.forEach(([k])=>$(`fp_${k}`).addEventListener('change',updateProcedureWarning)); updateProcedureWarning(); }
function updateProcedureWarning(){const ok=PROCEDURES.every(([k])=>$(`fp_${k}`)?.checked); const w=$('procedureWarning'); w.classList.toggle('ok',ok); w.textContent=ok?tr('ok'):tr('warn');}
function addAlternative(form=''){const id=`alt_${Date.now()}_${Math.random().toString(16).slice(2)}`; const div=document.createElement('div'); div.className='alt-card'; div.dataset.alt=id; div.innerHTML=`<div class="alt-head"><label class="field" style="flex:1">${tr('form')}<input class="interal-input alt-form" value="${esc(form)}"></label><button class="interal-btn interal-btn--secondary alt-remove" type="button">${tr('remove')}</button></div><div class="score-grid">${CRITERIA.map(([k])=>`<label class="field">${criterionLabel(k)}<input type="number" min="0" max="100" value="0" class="interal-input alt-score" data-k="${k}"></label>`).join('')}</div><div class="score-value">Manual selection score: <span class="alt-ms">0</span></div>`; $('altsBox').appendChild(div); div.querySelectorAll('input').forEach(i=>i.addEventListener('input',calculate)); div.querySelector('.alt-remove').addEventListener('click',()=>{div.remove();calculate();});}
function readLang(container,list,hasIpa){return Object.fromEntries(list.map(([c])=>[c,{word:$(`${container}_${c}_word`)?.value.trim()||'',...(hasIpa?{ipa:$(`${container}_${c}_ipa`)?.value.trim()||''}:{}),comment:$(`${container}_${c}_comment`)?.value.trim()||''}]))}
function readAlternatives(){return [...document.querySelectorAll('.alt-card')].map(card=>{const scores={}; CRITERIA.forEach(([k])=>scores[k]=num(card.querySelector(`[data-k="${k}"]`)?.value)); scores.manualSelectionScore=score(scores); card.querySelector('.alt-ms').textContent=scores.manualSelectionScore.toFixed(1); return {form:card.querySelector('.alt-form').value.trim(),scores};}).filter(a=>a.form)}
function collectState(){return {candidate:$('candidate').value.trim(),meaning:$('meaning').value.trim(),russian:$('russian').value.trim(),partOfSpeech:$('partOfSpeech').value.trim(),comment:$('comment').value.trim(),failedProcedures:Object.fromEntries(PROCEDURES.map(([k])=>[k,Boolean($(`fp_${k}`)?.checked)])),controlLanguages:readLang('controlBox',CONTROL,true),auxiliaryLanguages:readLang('auxBox',AUX,false),referenceLanguages:readLang('refBox',REF,false),alternatives:readAlternatives(),possibleDerivatives:$('derivatives').value.split(/,|\n/).map(s=>s.trim()).filter(Boolean)} }
function validate(st){if(!st.candidate)throw Error(tr('validationCandidate')); if(!st.meaning)throw Error(tr('validationMeaning')); if(!PROCEDURES.every(([k])=>st.failedProcedures[k]===true))throw Error(tr('validationProcedures'));}
function calculate(){const alts=readAlternatives(); const best=[...alts].sort((a,b)=>b.scores.manualSelectionScore-a.scores.manualSelectionScore)[0]||null; lastResult={procedure:'alter-vordes-step-6',section:CARD_SECTION,bestForm:best?.form||$('candidate').value.trim(),decision:best?'recommended':'weak',scores:best?.scores||{},alternatives:alts.map(a=>({...a,shortJustification:'Manual criteria scoring'})),risks:[],derivatives:$('derivatives').value.split(/,|\n/).map(s=>s.trim()).filter(Boolean),shortJustification:'Manual selection after failure of the five main procedures.',confidence:0,finalDecisionByHuman:true}; renderResult(lastResult); return lastResult;}
function renderResult(r){$('resultPanel').hidden=false; $('resultBox').innerHTML=`<div class="result-grid"><div class="result-cell"><b>${tr('best')}</b><br>${esc(r.bestForm||'—')}</div><div class="result-cell"><b>Manual selection score</b><br>${esc(r.scores?.manualSelectionScore??'—')}</div><div class="result-cell"><b>Decision</b><br>${esc(r.decision)}</div></div><h3>${tr('alternatives')}</h3><div class="table-wrap"><table><thead><tr><th>${tr('form')}</th><th>MS</th></tr></thead><tbody>${(r.alternatives||[]).map(a=>`<tr><td>${esc(a.form)}</td><td>${esc(a.scores?.manualSelectionScore??a.manualSelectionScore??'')}</td></tr>`).join('')}</tbody></table></div><p><b>${tr('risks')}:</b> ${esc((r.risks||[]).join('; ')||'—')}</p><p><b>${tr('derivatives')}:</b> ${esc((r.derivatives||[]).join(', ')||'—')}</p><p>${esc(r.shortJustification||'')}</p>`;}
async function createCard(){const st=collectState(); validate(st); const r=lastResult||calculate(); const id=CARD_PREFIX+uuid12(); const card={id,section:CARD_SECTION,type:'alter-vordes',algorithmStep:6,title:r.bestForm||st.candidate,selectedForm:r.bestForm||st.candidate,meaning:st.meaning,russian:st.russian,partOfSpeech:st.partOfSpeech,status:'candidate',discussionId:`card-${id}`,failedProcedures:st.failedProcedures,controlLanguages:st.controlLanguages,auxiliaryLanguages:st.auxiliaryLanguages,referenceLanguages:st.referenceLanguages,scores:{...r.scores,manualSelectionScore:score(r.scores||{})},alternatives:(r.alternatives||st.alternatives).map(a=>({form:a.form,manualSelectionScore:a.scores?.manualSelectionScore??a.manualSelectionScore})),risks:r.risks||[],possibleDerivatives:r.derivatives||st.possibleDerivatives,model:{name:'Qwen3-235B-A22B-FP8',role:'advisory evaluator',finalDecisionByHuman:true},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; let saved=card; try{const res=await fetch(`${API_BASE}/api/cards`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({section:CARD_SECTION,title:card.title,category:'alter-vordes',payload:card})}); const data=await res.json().catch(()=>null); if(!res.ok||!data?.ok)throw Error(data?.error||res.status); saved=data.card?.payload||{...card,id:data.id,discussionId:data.discussionId||`card-${data.id}`};}catch(e){console.warn('Alter vordes: card insert failed; using fallback sequential ID'); try{const res=await fetch(`${API_BASE}/api/cards-next-id?section=${CARD_SECTION}`); const data=await res.json(); if(data?.id)saved={...card,id:data.id,discussionId:`card-${data.id}`,fallbackMode:'fallback-sequential'};}catch{}} if(!saved.id.startsWith(CARD_PREFIX)) throw Error('Invalid card id prefix'); const text=JSON.stringify(saved,null,2); if(new Blob([text]).size>50000)throw Error('JSON card is larger than 50 KB'); lastCard=saved; $('jsonOutput').value=text; return saved;}
async function aiEvaluate(){try{const st=collectState(); validate(st); const payload={...st,alternatives:st.alternatives.map(a=>a.form)}; const res=await fetch(`${API_BASE}/api/alter-word-evaluate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data=await res.json(); if(!res.ok||!data?.ok) throw Error(data?.error||res.status); lastResult=data.result; renderResult(lastResult);}catch(e){console.warn('Alter vordes: AI evaluation failed; manual mode remains available'); alert(tr('aiUnavailable'));}}
async function encodeState(obj){const json=JSON.stringify({compressed:false,data:obj}); const bytes=new TextEncoder().encode(json); let bin=''; bytes.forEach(b=>bin+=String.fromCharCode(b)); return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function decodeState(s){const bin=atob(s.replace(/-/g,'+').replace(/_/g,'/')); const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)); return JSON.parse(new TextDecoder().decode(bytes)).data;}
async function copyLink(){const st=collectState(); const payload={source:'interal-form-draft',version:1,path:'/interal/altervordes/',fields:st}; try{const res=await fetch(`${API_BASE}/api/share-state`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:'/interal/altervordes/',payload})}); const data=await res.json(); if(!res.ok||!data?.url)throw Error(data?.error||res.status); await navigator.clipboard.writeText(data.url); return;}catch(e){console.warn('Alter vordes: Supabase insert failed; using fallback self-contained link');} const sid=(lastCard?.id||CARD_PREFIX+'000000000001').replace(CARD_PREFIX,''); const state=await encodeState(payload); const url=`${location.origin}${location.pathname}?sid=${encodeURIComponent(sid)}&state=${encodeURIComponent(state)}`; await navigator.clipboard.writeText(url);}
function fill(st){if(!st)return; ['candidate','meaning','russian','partOfSpeech','comment'].forEach(k=>{if($(k))$(k).value=st[k]||''}); PROCEDURES.forEach(([k])=>{if($(`fp_${k}`))$(`fp_${k}`).checked=!!st.failedProcedures?.[k]}); for(const [container,list] of [['controlBox',CONTROL],['auxBox',AUX],['refBox',REF]]) for(const [c] of list){const v=(container==='controlBox'?st.controlLanguages:container==='auxBox'?st.auxiliaryLanguages:st.referenceLanguages)?.[c]||{}; if($(`${container}_${c}_word`))$(`${container}_${c}_word`).value=v.word||''; if($(`${container}_${c}_ipa`))$(`${container}_${c}_ipa`).value=v.ipa||''; if($(`${container}_${c}_comment`))$(`${container}_${c}_comment`).value=v.comment||'';} $('altsBox').innerHTML=''; (st.alternatives?.length?st.alternatives:['manke','falta','briste','lakse']).forEach(a=>addAlternative(typeof a==='string'?a:a.form)); $('derivatives').value=(st.possibleDerivatives||[]).join(', '); updateProcedureWarning(); calculate();}

function applyI18n(){
  document.querySelector('.eyebrow').textContent=tr('eyebrow');
  document.querySelector('.alter-hero p:last-child').textContent=tr('lead');
  document.querySelector('.notice').textContent=tr('notice');
  const h=[...document.querySelectorAll('.panel h2')];
  ['basic','failedTitle','control','aux','ref','altTitle','derivativesTitle','result','jsonCard'].forEach((k,i)=>{ if(k&&h[i])h[i].textContent=tr(k); });
  const labels=[...document.querySelectorAll('.grid.two > .field')]; ['candidate','meaning','russian','pos','comment'].forEach((k,i)=>{ if(labels[i]) labels[i].firstChild.nodeValue=tr(k); });
  const ids={addAlt:'add',calculateBtn:'calculate',aiBtn:'ai',jsonBtn:'json',copyJsonBtn:'copyJson',downloadJsonBtn:'download',linkBtn:'link'};
  Object.entries(ids).forEach(([id,k])=>{ if($(id)) $(id).textContent=tr(k); });
  const human=document.querySelector('#resultPanel .warning'); if(human) human.textContent=tr('human');
  updateProcedureWarning();
}

async function restore(){const p=new URLSearchParams(location.search); if(p.get('state')){try{const payload=await decodeState(p.get('state')); fill(payload.fields||payload);}catch{}} else if(p.get('s')){try{const res=await fetch(`${API_BASE}/api/share-state?id=${encodeURIComponent(p.get('s'))}`); const data=await res.json(); if(data?.ok)fill(data.payload?.fields);}catch{}}}
document.addEventListener('DOMContentLoaded',()=>{applyI18n();renderProcedures();renderLang('controlBox',CONTROL,true);renderLang('auxBox',AUX,false);renderLang('refBox',REF,false);['manke','falta','briste','lakse'].forEach(addAlternative);document.body.addEventListener('input',()=>{calculate();});$('addAlt').onclick=()=>addAlternative();$('calculateBtn').onclick=()=>{try{validate(collectState());calculate();}catch(e){alert(e.message)}};$('aiBtn').onclick=aiEvaluate;$('jsonBtn').onclick=()=>createCard().catch(e=>alert(e.message));$('copyJsonBtn').onclick=async()=>{if(!$('jsonOutput').value)await createCard(); navigator.clipboard.writeText($('jsonOutput').value);};$('downloadJsonBtn').onclick=async()=>{if(!$('jsonOutput').value)await createCard(); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([$('jsonOutput').value],{type:'application/json'})); a.download=`${lastCard?.id||'altervordes'}.json`; a.click(); URL.revokeObjectURL(a.href);};$('linkBtn').onclick=()=>copyLink().catch(e=>alert(e.message));document.addEventListener('interal:languagechange',()=>{const fp=Object.fromEntries(PROCEDURES.map(([k])=>[k,Boolean($(`fp_${k}`)?.checked)]));applyI18n();renderProcedures();PROCEDURES.forEach(([k])=>{if($(`fp_${k}`))$(`fp_${k}`).checked=fp[k];});updateProcedureWarning();});restore();});
